#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H


/*功能码*/
#define FUNCTIONCODE_READ_HOLDREGISTER    0x03
#define FUNCTIONCODE_READ_INPUTREGISTER   0x04
#define FUNCTIONCODE_WRITE_MULREGISTER    0x10

/* 保持寄存器地址 */
#define HOLDREG_BASE_DEVICEPARAM 0x00

typedef enum {
	HOLDREGISTER_DEVICEPARAM_COMMAND = HOLDREG_BASE_DEVICEPARAM,
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT = HOLDREGISTER_DEVICEPARAM_COMMAND + 2,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM = HOLDREGISTER_DEVICEPARAM_BLINDZONE + 2,
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + 2,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + 2,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + 2,
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + 2,
    HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + 2,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE = HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + 2,
    HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION = HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG + 2,
    HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT = HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION + 2,
    HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT = HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD = HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + 2,
    HOLDREGISTER_DEVICEPARAM_CRC = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + 2,
	HOLEREGISTER_STOP = (HOLDREGISTER_DEVICEPARAM_CRC + 2) // 保持寄存器结束标志
} HOLD;

/*保持寄存器详细地址*/

/*输入寄存器详细地址*/


/* MeasurementResult 寄存器映射 */
/* 每个字段占 2 个保持寄存器 */
#define REG_SIZE_U32    2
#define REG_SIZE_FLOAT  2
#define REG_SIZE_I32    2
#define REG_SIZE_U8     2   /* 即使是 uint8 也占两个寄存器，方便对齐 */

/* ==== DeviceStatus ==== */
#define REG_DEVICE_STATUS_WORK_MODE             (0)
#define REG_DEVICE_STATUS_DEVICE_STATE          (REG_DEVICE_STATUS_WORK_MODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ERROR_CODE            (REG_DEVICE_STATUS_DEVICE_STATE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_CURRENT_COMMAND       (REG_DEVICE_STATUS_ERROR_CODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ZERO_POINT_STATUS     (REG_DEVICE_STATUS_CURRENT_COMMAND + REG_SIZE_U32)

/* ==== OilMeasurement ==== */
#define REG_OIL_MEASUREMENT_OIL_LEVEL           (REG_DEVICE_STATUS_ZERO_POINT_STATUS + REG_SIZE_U8)
#define REG_OIL_MEASUREMENT_AIR_FREQUENCY       (REG_OIL_MEASUREMENT_OIL_LEVEL + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_OIL_FREQUENCY       (REG_OIL_MEASUREMENT_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY    (REG_OIL_MEASUREMENT_OIL_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_CURRENT_FREQUENCY   (REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY + REG_SIZE_U32)

/* ==== WaterMeasurement ==== */
#define REG_WATER_MEASUREMENT_WATER_LEVEL       (REG_OIL_MEASUREMENT_CURRENT_FREQUENCY + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_ZERO_CAPACITANCE  (REG_WATER_MEASUREMENT_WATER_LEVEL + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_OIL_CAPACITANCE   (REG_WATER_MEASUREMENT_ZERO_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE (REG_WATER_MEASUREMENT_OIL_CAPACITANCE + REG_SIZE_FLOAT)

/* ==== ZeroCalibration ==== */
#define REG_ZERO_CALIBRATION_TURNS              (REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_ZERO_CALIBRATION_VALUE              (REG_ZERO_CALIBRATION_TURNS + REG_SIZE_U32)

/* ==== ActualHeightMeasurement ==== */
#define REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL (REG_ZERO_CALIBRATION_VALUE + REG_SIZE_U32)
#define REG_HEIGHT_MEASUREMENT_CURRENT_REAL     (REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL + REG_SIZE_U32)

/* ==== Debug Data ==== */
#define REG_DEBUG_DATA_BASE                     (REG_HEIGHT_MEASUREMENT_CURRENT_REAL + REG_SIZE_U32)
#define REG_DEBUG_CURRENT_ENCODER               (REG_DEBUG_DATA_BASE + 0)
#define REG_DEBUG_SENSOR_POSITION               (REG_DEBUG_CURRENT_ENCODER + REG_SIZE_I32)
#define REG_DEBUG_CABLE_LENGTH                  (REG_DEBUG_SENSOR_POSITION + REG_SIZE_I32)
#define REG_DEBUG_FREQUENCY                     (REG_DEBUG_CABLE_LENGTH + REG_SIZE_U32)
#define REG_DEBUG_TEMPERATURE                   (REG_DEBUG_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_AIR_FREQUENCY                 (REG_DEBUG_TEMPERATURE + REG_SIZE_U32)
#define REG_DEBUG_CURRENT_AMPLITUDE             (REG_DEBUG_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_WATER_LEVEL_VOLTAGE           (REG_DEBUG_CURRENT_AMPLITUDE + REG_SIZE_U32)

/* ==== Single Point Measurement ==== */
#define REG_SINGLE_POINT_MEAS_TEMP              (REG_DEBUG_WATER_LEVEL_VOLTAGE + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_DENSITY           (REG_SINGLE_POINT_MEAS_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_TEMP_POS          (REG_SINGLE_POINT_MEAS_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_STD_DENSITY       (REG_SINGLE_POINT_MEAS_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_VCF20             (REG_SINGLE_POINT_MEAS_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY    (REG_SINGLE_POINT_MEAS_VCF20 + REG_SIZE_U32)

/* ==== Single Point Monitoring ==== */
#define REG_SINGLE_POINT_MON_TEMP               (REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_DENSITY            (REG_SINGLE_POINT_MON_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_TEMP_POS           (REG_SINGLE_POINT_MON_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_STD_DENSITY        (REG_SINGLE_POINT_MON_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_VCF20              (REG_SINGLE_POINT_MON_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_WEIGHT_DENSITY     (REG_SINGLE_POINT_MON_VCF20 + REG_SIZE_U32)

/* ==== Density Distribution Averages ==== */
#define REG_DENSITY_DIST_AVG_TEMP               (REG_SINGLE_POINT_MON_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_DENSITY            (REG_DENSITY_DIST_AVG_TEMP + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_STD_DENSITY        (REG_DENSITY_DIST_AVG_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_VCF20              (REG_DENSITY_DIST_AVG_STD_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_WEIGHT_DENSITY     (REG_DENSITY_DIST_AVG_VCF20 + REG_SIZE_U32)
#define REG_DENSITY_DIST_MEAS_POINTS            (REG_DENSITY_DIST_AVG_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_OIL_LEVEL              (REG_DENSITY_DIST_MEAS_POINTS + REG_SIZE_U32)

/* ==== Density Distribution Single Data ==== */
#define REG_DENSITY_DIST_POINT_BASE             (REG_DENSITY_DIST_OIL_LEVEL + REG_SIZE_U32)
#define REG_DENSITY_DIST_POINT_SIZE             (6 * REG_SIZE_U32) /* 温度、密度、温度位置、标准密度、VCF20、计重密度 */

#define REG_DENSITY_POINT_TEMP(i)               (REG_DENSITY_DIST_POINT_BASE + (i) * REG_DENSITY_DIST_POINT_SIZE)
#define REG_DENSITY_POINT_DENSITY(i)            (REG_DENSITY_POINT_TEMP(i) + REG_SIZE_U32)
#define REG_DENSITY_POINT_TEMP_POS(i)           (REG_DENSITY_POINT_TEMP(i) + 2 * REG_SIZE_U32)
#define REG_DENSITY_POINT_STD_DENSITY(i)        (REG_DENSITY_POINT_TEMP(i) + 3 * REG_SIZE_U32)
#define REG_DENSITY_POINT_VCF20(i)              (REG_DENSITY_POINT_TEMP(i) + 4 * REG_SIZE_U32)
#define REG_DENSITY_POINT_WEIGHT_DENSITY(i)     (REG_DENSITY_POINT_TEMP(i) + 5 * REG_SIZE_U32)


#define REG_ENG (REG_DENSITY_DIST_POINT_BASE + 100 * REG_DENSITY_DIST_POINT_SIZE)


#define INPUTREGISTER_AMOUNT (REG_ENG)




/*报警状态*/
#define ALARMSTATE_NONE 0
#define ALARMSTATE_LOW 1
#define ALARMSTATE_HIGH 2

/*平均温度状态*/
#define AVETEMPERATURESTATE_UNVALID 0
#define AVETEMPERATURESTATE_VALID 1

/*平均密度状态*/
#define AVERAGEDENSITY_UNVALID 0
#define AVERAGEDENSITY_VALID 1

/*水位状态*/
#define WATER_UNVALID 0
#define WATER_VALID 1


#endif
