#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H


/*功能码*/
#define FUNCTIONCODE_READ_HOLDREGISTER    0x03
#define FUNCTIONCODE_READ_INPUTREGISTER   0x04
#define FUNCTIONCODE_WRITE_MULREGISTER    0x10

/* 保持寄存器地址 */
#define HOLDREG_BASE_DEVICEPARAM 0x00

/* 约定: 每个 32 位参数占用 2 个保持寄存器 (16bit * 2) */
#define REG_STRIDE 2

typedef enum
{
    /* 指令 */
    HOLDREGISTER_DEVICEPARAM_COMMAND                       = HOLDREG_BASE_DEVICEPARAM,

    /* 基础参数 */
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT                    = HOLDREGISTER_DEVICEPARAM_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE                     = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE               = HOLDREGISTER_DEVICEPARAM_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM= HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED               = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE                    = HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSORID                      = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION       = HOLDREGISTER_DEVICEPARAM_SENSORID + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION               = HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND      = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE        = HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM   = HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM             = HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED1                     = HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED2                     = HOLDREGISTER_DEVICEPARAM_RESERVED1 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED3                     = HOLDREGISTER_DEVICEPARAM_RESERVED2 + REG_STRIDE,

    /* 称重参数 */
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT                  = HOLDREGISTER_DEVICEPARAM_RESERVED3 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT                   = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO      = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO      = HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT      = HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT      = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT       = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT       = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED4                     = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED5                     = HOLDREGISTER_DEVICEPARAM_RESERVED4 + REG_STRIDE,

    /* 指令参数 */
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL           = HOLDREGISTER_DEVICEPARAM_RESERVED5 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL         = HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION              = HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL + REG_STRIDE,   /* 单点测量位置 */
    HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION           = HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION + REG_STRIDE,        /* 单点监测位置 */
    HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL= HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE        = HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED6                     = HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED7                     = HOLDREGISTER_DEVICEPARAM_RESERVED6 + REG_STRIDE,

    /* 密度与温度修正 */
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION             = HOLDREGISTER_DEVICEPARAM_RESERVED7 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION         = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + REG_STRIDE,

    /* 分布测量参数 */
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT      = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT       = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY     = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER        = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE         = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT        = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE     = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT                = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT             = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME       = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED8                     = HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED9                     = HOLDREGISTER_DEVICEPARAM_RESERVED8 + REG_STRIDE,

    /* Wartsila 密度区间测量参数 */
    HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT  = HOLDREGISTER_DEVICEPARAM_RESERVED9 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT  = HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL     = HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE = HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL + REG_STRIDE,

    /* 水位测量参数 */
    HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION          = HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE               = HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED10                    = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + REG_STRIDE,

    /* 实高测量参数 */
    HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG         = HOLDREGISTER_DEVICEPARAM_RESERVED10 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION        = HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT             = HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT             = HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT + REG_STRIDE,

    /* 液位测量参数 */
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD             = HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD  = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD + REG_STRIDE,

    /* 报警 DO */
    HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_DO                 = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_LOW_DO                  = HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_DO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_THIRD_STATE_THRESHOLD         = HOLDREGISTER_DEVICEPARAM_ALARM_LOW_DO + REG_STRIDE,

    /* 4-20mA 输出与报警 AO */
    HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_START_mA        = HOLDREGISTER_DEVICEPARAM_THIRD_STATE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_END_mA          = HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_START_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_AO                 = HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_END_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_LOW_AO                  = HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_AO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA            = HOLDREGISTER_DEVICEPARAM_ALARM_LOW_AO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA            = HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA             = HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA              = HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA              = HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA + REG_STRIDE,

    /* 元信息和 CRC */
    HOLDREGISTER_DEVICEPARAM_PARAM_VERSION                 = HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE                   = HOLDREGISTER_DEVICEPARAM_PARAM_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAGIC                         = HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CRC                           = HOLDREGISTER_DEVICEPARAM_MAGIC + REG_STRIDE,

    /* 结束标志: 下一个可用的保持寄存器地址 */
    HOLEREGISTER_STOP                                      = HOLDREGISTER_DEVICEPARAM_CRC + REG_STRIDE
} HOLD;


/*保持寄存器详细地址*/

/*输入寄存器详细地址*/

/* 输入寄存器详细地址 */

/* 每个字段占 2 个保持寄存器 */
#define REG_SIZE_U32    2
#define REG_SIZE_FLOAT  2
#define REG_SIZE_I32    2
#define REG_SIZE_U8     2   /* uint8 也占两个寄存器，保持对齐一致 */

/* ==== DeviceStatus ==== */
#define REG_DEVICE_STATUS_WORK_MODE             (0)
#define REG_DEVICE_STATUS_DEVICE_STATE          (REG_DEVICE_STATUS_WORK_MODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ERROR_CODE            (REG_DEVICE_STATUS_DEVICE_STATE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_CURRENT_COMMAND       (REG_DEVICE_STATUS_ERROR_CODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ZERO_POINT_STATUS     (REG_DEVICE_STATUS_CURRENT_COMMAND + REG_SIZE_U32)

/* ==== DebugData ==== */
#define REG_DEBUG_BASE                          (REG_DEVICE_STATUS_ZERO_POINT_STATUS + REG_SIZE_U32)

#define REG_DEBUG_CURRENT_ENCODER               (REG_DEBUG_BASE + 0)
#define REG_DEBUG_SENSOR_POSITION               (REG_DEBUG_CURRENT_ENCODER + REG_SIZE_I32)
#define REG_DEBUG_CABLE_LENGTH                  (REG_DEBUG_SENSOR_POSITION + REG_SIZE_I32)

#define REG_DEBUG_FREQUENCY                     (REG_DEBUG_CABLE_LENGTH + REG_SIZE_I32)
#define REG_DEBUG_TEMPERATURE                   (REG_DEBUG_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_AIR_FREQUENCY                 (REG_DEBUG_TEMPERATURE + REG_SIZE_U32)
#define REG_DEBUG_CURRENT_AMPLITUDE             (REG_DEBUG_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_WATER_LEVEL_VOLTAGE           (REG_DEBUG_CURRENT_AMPLITUDE + REG_SIZE_U32)

#define REG_DEBUG_CURRENT_WEIGHT                (REG_DEBUG_WATER_LEVEL_VOLTAGE + REG_SIZE_U32)
#define REG_DEBUG_WEIGHT_PARAM                  (REG_DEBUG_CURRENT_WEIGHT + REG_SIZE_U32)

#define REG_DEBUG_ANGLE_X                       (REG_DEBUG_WEIGHT_PARAM + REG_SIZE_U32)
#define REG_DEBUG_ANGLE_Y                       (REG_DEBUG_ANGLE_X + REG_SIZE_I32)

#define REG_DEBUG_MOTOR_SPEED                   (REG_DEBUG_ANGLE_Y + REG_SIZE_I32)
#define REG_DEBUG_MOTOR_STATE                   (REG_DEBUG_MOTOR_SPEED + REG_SIZE_U32)

/* ==== OilMeasurement ==== */
#define REG_OIL_MEASUREMENT_OIL_LEVEL           (REG_DEBUG_MOTOR_STATE + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_AIR_FREQUENCY       (REG_OIL_MEASUREMENT_OIL_LEVEL + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_OIL_FREQUENCY       (REG_OIL_MEASUREMENT_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY    (REG_OIL_MEASUREMENT_OIL_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_CURRENT_FREQUENCY   (REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY + REG_SIZE_U32)

/* ==== WaterMeasurement ==== */
#define REG_WATER_MEASUREMENT_WATER_LEVEL       (REG_OIL_MEASUREMENT_CURRENT_FREQUENCY + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_ZERO_CAPACITANCE  (REG_WATER_MEASUREMENT_WATER_LEVEL + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_OIL_CAPACITANCE   (REG_WATER_MEASUREMENT_ZERO_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE (REG_WATER_MEASUREMENT_OIL_CAPACITANCE + REG_SIZE_FLOAT)

/* ==== ActualHeightMeasurement ==== */
#define REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL (REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_HEIGHT_MEASUREMENT_CURRENT_REAL     (REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL + REG_SIZE_U32)

/* ==== Single Point Measurement ==== */
#define REG_SINGLE_POINT_MEAS_TEMP              (REG_HEIGHT_MEASUREMENT_CURRENT_REAL + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_DENSITY           (REG_SINGLE_POINT_MEAS_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_TEMP_POS          (REG_SINGLE_POINT_MEAS_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_STD_DENSITY       (REG_SINGLE_POINT_MEAS_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_VCF20             (REG_SINGLE_POINT_MEAS_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY    (REG_SINGLE_POINT_MEAS_VCF20 + REG_SIZE_U32)

/* ==== Single Point Monitoring ==== */
#define REG_SINGLE_POINT_MON_TEMP               (REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_DENSITY            (REG_SINGLE_POINT_MON_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_TEMP_POS           (REG_SINGLE_POINT_MON_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_STD_DENSITY        (REG_SINGLE_POINT_MON_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_VCF20              (REG_SINGLE_POINT_MON_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_WEIGHT_DENSITY     (REG_SINGLE_POINT_MON_VCF20 + REG_SIZE_U32)

/* ==== Density Distribution Averages ==== */
#define REG_DENSITY_DIST_AVG_TEMP               (REG_SINGLE_POINT_MON_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_DENSITY            (REG_DENSITY_DIST_AVG_TEMP + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_STD_DENSITY        (REG_DENSITY_DIST_AVG_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_VCF20              (REG_DENSITY_DIST_AVG_STD_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_WEIGHT_DENSITY     (REG_DENSITY_DIST_AVG_VCF20 + REG_SIZE_U32)
#define REG_DENSITY_DIST_MEAS_POINTS            (REG_DENSITY_DIST_AVG_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_OIL_LEVEL              (REG_DENSITY_DIST_MEAS_POINTS + REG_SIZE_U32)

/* ==== Density Distribution Single Data ==== */
#define REG_DENSITY_DIST_POINT_BASE             (REG_DENSITY_DIST_OIL_LEVEL + REG_SIZE_U32)
#define REG_DENSITY_DIST_POINT_SIZE             (6 * REG_SIZE_U32) /* 每个测量点6个uint32 */

#define REG_DENSITY_POINT_TEMP(i)               (REG_DENSITY_DIST_POINT_BASE + (i) * REG_DENSITY_DIST_POINT_SIZE)
#define REG_DENSITY_POINT_DENSITY(i)            (REG_DENSITY_POINT_TEMP(i) + REG_SIZE_U32)
#define REG_DENSITY_POINT_TEMP_POS(i)           (REG_DENSITY_POINT_TEMP(i) + 2 * REG_SIZE_U32)
#define REG_DENSITY_POINT_STD_DENSITY(i)        (REG_DENSITY_POINT_TEMP(i) + 3 * REG_SIZE_U32)
#define REG_DENSITY_POINT_VCF20(i)              (REG_DENSITY_POINT_TEMP(i) + 4 * REG_SIZE_U32)
#define REG_DENSITY_POINT_WEIGHT_DENSITY(i)     (REG_DENSITY_POINT_TEMP(i) + 5 * REG_SIZE_U32)

/* ==== 最终寄存器数量 ==== */
#define REG_ENG (REG_DENSITY_DIST_POINT_BASE + MAX_MEASUREMENT_POINTS * REG_DENSITY_DIST_POINT_SIZE)

#define INPUTREGISTER_AMOUNT (REG_ENG)




/*报警状态*/
#define ALARMSTATE_NONE 0
#define ALARMSTATE_LOW 1
#define ALARMSTATE_HIGH 2

/*平均温度状态*/
#define AVETEMPERATURESTATE_UNVALID 0
#define AVETEMPERATURESTATE_VALID 1

/*平均密度状态*/
#define AVERAGEDENSITY_UNVALID 0
#define AVERAGEDENSITY_VALID 1

/*水位状态*/
#define WATER_UNVALID 0
#define WATER_VALID 1


#endif
