#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H

#include <stdbool.h>
#include <stdint.h>

/* 标准Modbus功能码 */
#define FUNCTIONCODE_READ_HOLDREGISTER  0x03U
#define FUNCTIONCODE_READ_INPUTREGISTER 0x04U
#define FUNCTIONCODE_WRITE_MULREGISTER  0x10U

/* CPU2/CPU3共享标量统一占两个16位寄存器，高字在前 */
#define REG_STRIDE    2U
#define REG_SIZE_U32  2U
#define REG_SIZE_I32  2U
#define REG_SIZE_FLOAT 2U
#define REG_SIZE_U8   2U

#define LTD_MODBUS_MAX_READ_REGISTERS  125U
#define LTD_MODBUS_MAX_WRITE_REGISTERS 122U

/* 保持寄存器按功能分块，块内未使用地址继续保留 */
#define HOLDREG_BASE_GENERAL      0x0000U
#define HOLDREG_BASE_MOTOR        0x0100U
#define HOLDREG_BASE_OIL_HEIGHT   0x0200U
#define HOLDREG_BASE_WATER        0x0300U
#define HOLDREG_BASE_CORRECTION   0x0400U
#define HOLDREG_BASE_MEAS_CONFIG  0x0500U
#define HOLDREG_BASE_AO           0x0600U
#define HOLDREG_BASE_RELAY        0x0700U
#define HOLDREG_BASE_SI_WARTSILA  0x0800U
#define HOLDREG_BASE_RESERVED     0x0900U
#define HOLDREG_BASE_METADATA     0x0E00U
#define HOLDREG_BASE_COMMAND      0x0F00U
#define HOLDREGISTER_AMOUNT       0x1000U

#define HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT 4U
#define HOLDREGISTER_RELAY_ALARM_FIELD_COUNT 13U
#define HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT \
    (HOLDREGISTER_RELAY_ALARM_FIELD_COUNT * REG_STRIDE)

/*
 * CPU2保持寄存器地址表。
 * 标准Modbus PDU地址直接作为CPU2/CPU3寄存器数组索引。
 */
typedef enum
{
    /* 设备信息与通用参数：0x0000 */
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE = HOLDREG_BASE_GENERAL,
    HOLDREGISTER_DEVICEPARAM_SENSORID = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION = HOLDREGISTER_DEVICEPARAM_SENSORID + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION = HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO = HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT = HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_PROTOCOL_VERSION = HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FAULT_AUTO_RECOVERY_RETRY_LIMIT = HOLDREGISTER_DEVICEPARAM_PROTOCOL_VERSION + REG_STRIDE,

    /* 电机、编码器、重量与零点参数：0x0100 */
    HOLDREGISTER_DEVICEPARAM_POSITION_SOURCE_AUTO_SWITCH = HOLDREG_BASE_MOTOR,
    HOLDREGISTER_DEVICEPARAM_MOTOR_CURRENT = HOLDREGISTER_DEVICEPARAM_POSITION_SOURCE_AUTO_SWITCH + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM = HOLDREGISTER_DEVICEPARAM_MOTOR_CURRENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM = HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM = HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POSITION_COUNT_MODE = HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COUNT_FIRST_LOOP_CIRC = HOLDREGISTER_DEVICEPARAM_POSITION_COUNT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT = HOLDREGISTER_DEVICEPARAM_MOTOR_COUNT_FIRST_LOOP_CIRC + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO = HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO = HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE = HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE = HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE = HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE + REG_STRIDE,

    /* 液位与罐高参数：0x0200 */
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT = HOLDREG_BASE_OIL_HEIGHT,
    HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE = HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD = HOLDREGISTER_DEVICEPARAM_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY = HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME = HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD = HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD = HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG = HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION = HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT = HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT = HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_ENABLE = HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT + REG_STRIDE,

    /* 水位参数：0x0300 */
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_HYSTERESIS_TIME = HOLDREG_BASE_WATER,
    HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_HYSTERESIS_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE = HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD = HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_FIND_CAP_THRESHOLD = HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE = HOLDREGISTER_DEVICEPARAM_WATER_FIND_CAP_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ZERO_CAP = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD = HOLDREGISTER_DEVICEPARAM_ZERO_CAP + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION = HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LAG_CAP_THRESHOLD = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION + REG_STRIDE,

    /* 密度、温度与钢带修正参数：0x0400 */
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION = HOLDREG_BASE_CORRECTION,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE = HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT = HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE = HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT + REG_STRIDE,

    /* 测量与标定参数：0x0500 */
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT = HOLDREG_BASE_MEAS_CONFIG,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT = HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT = HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL = HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL = HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_TANK_HEIGHT = HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION = HOLDREGISTER_DEVICEPARAM_CALIBRATE_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION = HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL = HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE = HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL + REG_STRIDE,

    /* AO参数：0x0600 */
    HOLDREGISTER_DEVICEPARAM_AO_WORK_MODE = HOLDREG_BASE_AO,
    HOLDREGISTER_DEVICEPARAM_AO_CURRENT_MODE = HOLDREGISTER_DEVICEPARAM_AO_WORK_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_OUTPUT_SOURCE = HOLDREGISTER_DEVICEPARAM_AO_CURRENT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_CURRENT_CORRECTION_MA_X100 = HOLDREGISTER_DEVICEPARAM_AO_OUTPUT_SOURCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_FIXED_CURRENT_MA_X100 = HOLDREGISTER_DEVICEPARAM_AO_CURRENT_CORRECTION_MA_X100 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_RANGE_0_01MM = HOLDREGISTER_DEVICEPARAM_AO_FIXED_CURRENT_MA_X100 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_RANGE_100_01MM = HOLDREGISTER_DEVICEPARAM_AO_RANGE_0_01MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_DAMPING_X10_S = HOLDREGISTER_DEVICEPARAM_AO_RANGE_100_01MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_FAULT_MODE = HOLDREGISTER_DEVICEPARAM_AO_DAMPING_X10_S + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_FAULT_CURRENT_MA_X100 = HOLDREGISTER_DEVICEPARAM_AO_FAULT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_ERROR_LEVEL = HOLDREGISTER_DEVICEPARAM_AO_FAULT_CURRENT_MA_X100 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_POWER_ON_CURRENT_MA_X100 = HOLDREGISTER_DEVICEPARAM_AO_ERROR_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_SIMULATION_CURRENT_MA_X100 = HOLDREGISTER_DEVICEPARAM_AO_POWER_ON_CURRENT_MA_X100 + REG_STRIDE,
    HOLDREGISTER_AO_SIMULATION_ENABLE = HOLDREGISTER_DEVICEPARAM_AO_SIMULATION_CURRENT_MA_X100 + REG_STRIDE,

    /* 4路继电器配置参数：0x0700 */
    HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE = HOLDREG_BASE_RELAY,
    HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_END = HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE +
        (HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT),

    /* Wartsila与SI参数：0x0800 */
    HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT = HOLDREG_BASE_SI_WARTSILA,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT = HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL = HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE = HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_BOTTOM_DETECT_INTERVAL = HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_TANK_HEIGHT = HOLDREGISTER_DEVICEPARAM_WARTSILA_BOTTOM_DETECT_INTERVAL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SI_PROFILE_FIRST_POINT = HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SI_PROFILE_INCREMENT = HOLDREGISTER_DEVICEPARAM_SI_PROFILE_FIRST_POINT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SI_PROFILE_DWELL_TIME = HOLDREGISTER_DEVICEPARAM_SI_PROFILE_INCREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SI_PROFILE_BOTTOM_DETECT_INTERVAL = HOLDREGISTER_DEVICEPARAM_SI_PROFILE_DWELL_TIME + REG_STRIDE,

    /* 原参数结构保留字段：0x0900 */
    HOLDREGISTER_DEVICEPARAM_RESERVED8 = HOLDREG_BASE_RESERVED,
    HOLDREGISTER_DEVICEPARAM_RESERVED9 = HOLDREGISTER_DEVICEPARAM_RESERVED8 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED10 = HOLDREGISTER_DEVICEPARAM_RESERVED9 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED11 = HOLDREGISTER_DEVICEPARAM_RESERVED10 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED18 = HOLDREGISTER_DEVICEPARAM_RESERVED11 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED19 = HOLDREGISTER_DEVICEPARAM_RESERVED18 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED20 = HOLDREGISTER_DEVICEPARAM_RESERVED19 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED21 = HOLDREGISTER_DEVICEPARAM_RESERVED20 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED28 = HOLDREGISTER_DEVICEPARAM_RESERVED21 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED29 = HOLDREGISTER_DEVICEPARAM_RESERVED28 + REG_STRIDE,

    /* 参数存储元信息，只读：0x0E00 */
    HOLDREGISTER_DEVICEPARAM_PARAM_VERSION = HOLDREG_BASE_METADATA,
    HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE = HOLDREGISTER_DEVICEPARAM_PARAM_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAGIC = HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CRC = HOLDREGISTER_DEVICEPARAM_MAGIC + REG_STRIDE,

    /* 命令入口与能力位：0x0F00 */
    HOLDREGISTER_DEVICEPARAM_COMMAND = HOLDREG_BASE_COMMAND,
    HOLDREGISTER_PROTOCOL_CAPABILITIES = HOLDREG_BASE_COMMAND + 0x0010U,

    HOLEREGISTER_STOP = HOLDREGISTER_AMOUNT
} HOLD;

#define HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT))
#define HOLDREGISTER_DEVICEPARAM_RELAY_DIGITAL_SOURCE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (1U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_CONTACT_TYPE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (2U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_MODE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (3U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_ERROR_VALUE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (4U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_SOURCE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (5U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_HH_ALARM_VALUE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (6U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_H_ALARM_VALUE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (7U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_L_ALARM_VALUE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (8U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_LL_ALARM_VALUE(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (9U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_HYSTERESIS(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (10U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_DAMPING_FACTOR(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (11U * REG_STRIDE))
#define HOLDREGISTER_DEVICEPARAM_RELAY_CLEAR_ALARM(ch) \
    (HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch) + (12U * REG_STRIDE))

/* 能力位序号固定；双端仅在对应业务闭环已经实现后发布。 */
#define LTD_CAPABILITY_MAINTENANCE_MODE                 (1UL << 0)
#define LTD_CAPABILITY_RELAY_ALARM_ACTION_STATUS        (1UL << 1)
#define LTD_CAPABILITY_RELAY_ALARM_INHIBIT              (1UL << 2)
#define LTD_CAPABILITY_AO_FAULT_CURRENT_INHIBIT         (1UL << 3)
#define LTD_CAPABILITY_CLEAR_ALL_RELAY_LATCHED_ALARMS   (1UL << 4)
#define LTD_CAPABILITY_SUPPORTED_MASK                   \
    (LTD_CAPABILITY_MAINTENANCE_MODE |                  \
     LTD_CAPABILITY_RELAY_ALARM_ACTION_STATUS |         \
     LTD_CAPABILITY_RELAY_ALARM_INHIBIT |               \
     LTD_CAPABILITY_AO_FAULT_CURRENT_INHIBIT |          \
     LTD_CAPABILITY_CLEAR_ALL_RELAY_LATCHED_ALARMS)

/* 输入寄存器按功能分块 */
#define INPUTREG_BASE_STATUS          0x0000U
#define INPUTREG_BASE_DEBUG           0x0100U
#define INPUTREG_BASE_PROCESS         0x1000U
#define INPUTREG_BASE_FIXED_RESULTS   0x1100U
#define INPUTREG_BASE_AO_RUNTIME      0x1400U
#define INPUTREG_BASE_RELAY_RUNTIME   0x1500U
#define INPUTREG_BASE_WIRELESS        0x1600U
#define INPUTREG_BASE_DENSITY_POINTS  0x2000U
#define INPUTREGISTER_AMOUNT          0x2A00U

/* CPU2权威状态，同一快照发布 */
#define REG_DEVICE_STATUS_WORK_MODE                    (INPUTREG_BASE_STATUS + 0x00U)
#define REG_DEVICE_STATUS_DEVICE_STATE                 (INPUTREG_BASE_STATUS + 0x02U)
#define REG_DEVICE_STATUS_ERROR_CODE                   (INPUTREG_BASE_STATUS + 0x04U)
#define REG_DEVICE_STATUS_CURRENT_COMMAND              (INPUTREG_BASE_STATUS + 0x06U)
#define REG_DEVICE_STATUS_ZERO_POINT_STATUS            (INPUTREG_BASE_STATUS + 0x08U)
#define REG_DEVICE_STATUS_PARAM_UPDATE_FLAG            (INPUTREG_BASE_STATUS + 0x0AU)
#define REG_DEVICE_STATUS_LOADING_UNLOADING_ACTIVE     (INPUTREG_BASE_STATUS + 0x0CU)
#define REG_DEVICE_STATUS_MANUAL_ALARM_INHIBIT         (INPUTREG_BASE_STATUS + 0x0EU)
#define REG_MAINTENANCE_MODE_ACTIVE                    (INPUTREG_BASE_STATUS + 0x10U)
#define REG_RELAY_ALARM_INHIBIT_EFFECTIVE              (INPUTREG_BASE_STATUS + 0x12U)
#define REG_RELAY_ALARM_ACTION_CHANNEL1                (INPUTREG_BASE_STATUS + 0x14U)
#define REG_RELAY_ALARM_ACTION_CHANNEL2                (INPUTREG_BASE_STATUS + 0x16U)
#define REG_RELAY_ALARM_ACTION_CHANNEL3                (INPUTREG_BASE_STATUS + 0x18U)
#define REG_RELAY_ALARM_ACTION_CHANNEL4                (INPUTREG_BASE_STATUS + 0x1AU)
#define REG_OIL_MEASUREMENT_PROBE_AT_LIQUID_LEVEL      (INPUTREG_BASE_STATUS + 0x1CU)
#define REG_OIL_MEASUREMENT_LIQUID_STABLE              (INPUTREG_BASE_STATUS + 0x1EU)
#define REG_OIL_MEASUREMENT_MANUAL_LEVEL_UPDATE_INHIBIT (INPUTREG_BASE_STATUS + 0x20U)
#define REG_HEIGHT_MEASUREMENT_BOTTOM_REFERENCE_VALID  (INPUTREG_BASE_STATUS + 0x22U)
#define REG_SINGLE_POINT_MEAS_COMPLETE_COUNTER         (INPUTREG_BASE_STATUS + 0x30U)
#define REG_SINGLE_POINT_MON_SAMPLE_COUNTER            (INPUTREG_BASE_STATUS + 0x32U)

/* 未来物理触点反馈槽；当前不支持，固定返回0 */
#define REG_RELAY_CONTACT_FEEDBACK_CHANNEL1_RESERVED   (INPUTREG_BASE_STATUS + 0x34U)
#define REG_RELAY_CONTACT_FEEDBACK_CHANNEL2_RESERVED   (INPUTREG_BASE_STATUS + 0x36U)
#define REG_RELAY_CONTACT_FEEDBACK_CHANNEL3_RESERVED   (INPUTREG_BASE_STATUS + 0x38U)
#define REG_RELAY_CONTACT_FEEDBACK_CHANNEL4_RESERVED   (INPUTREG_BASE_STATUS + 0x3AU)
#define REG_DEVICE_STATUS_BLOCK_END                    (INPUTREG_BASE_STATUS + 0x3CU)

/* 调试数据快照：0x0100 */
#define REG_DEBUG_BASE                INPUTREG_BASE_DEBUG
#define REG_DEBUG_CURRENT_ENCODER     (REG_DEBUG_BASE + 0x00U)
#define REG_DEBUG_SENSOR_POSITION     (REG_DEBUG_BASE + 0x02U)
#define REG_DEBUG_CABLE_LENGTH        (REG_DEBUG_BASE + 0x04U)
#define REG_DEBUG_MOTOR_STEP          (REG_DEBUG_BASE + 0x06U)
#define REG_DEBUG_MOTOR_DISTANCE      (REG_DEBUG_BASE + 0x08U)
#define REG_DEBUG_FREQUENCY           (REG_DEBUG_BASE + 0x0AU)
#define REG_DEBUG_TEMPERATURE         (REG_DEBUG_BASE + 0x0CU)
#define REG_DEBUG_AIR_FREQUENCY       (REG_DEBUG_BASE + 0x0EU)
#define REG_DEBUG_CURRENT_AMPLITUDE   (REG_DEBUG_BASE + 0x10U)
#define REG_DEBUG_WATER_CAPACITANCE_X10 (REG_DEBUG_BASE + 0x12U)
#define REG_DEBUG_CURRENT_WEIGHT      (REG_DEBUG_BASE + 0x14U)
#define REG_DEBUG_WEIGHT_PARAM        (REG_DEBUG_BASE + 0x16U)
#define REG_DEBUG_ANGLE_X             (REG_DEBUG_BASE + 0x18U)
#define REG_DEBUG_ANGLE_Y             (REG_DEBUG_BASE + 0x1AU)
#define REG_DEBUG_MOTOR_SPEED         (REG_DEBUG_BASE + 0x1CU)
#define REG_DEBUG_MOTOR_STATE         (REG_DEBUG_BASE + 0x1EU)
#define REG_DEBUG_BLOCK_END           (REG_DEBUG_BASE + 0x20U)

/* 液位、水位与罐高运行数据：0x1000 */
#define REG_OIL_MEASUREMENT_OIL_LEVEL             (INPUTREG_BASE_PROCESS + 0x00U)
#define REG_OIL_MEASUREMENT_AIR_FREQUENCY         (INPUTREG_BASE_PROCESS + 0x02U)
#define REG_OIL_MEASUREMENT_OIL_FREQUENCY         (INPUTREG_BASE_PROCESS + 0x04U)
#define REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY      (INPUTREG_BASE_PROCESS + 0x06U)
#define REG_OIL_MEASUREMENT_CURRENT_FREQUENCY     (INPUTREG_BASE_PROCESS + 0x08U)
#define REG_WATER_MEASUREMENT_WATER_LEVEL          (INPUTREG_BASE_PROCESS + 0x0AU)
#define REG_WATER_MEASUREMENT_ZERO_CAPACITANCE     (INPUTREG_BASE_PROCESS + 0x0CU)
#define REG_WATER_MEASUREMENT_OIL_CAPACITANCE      (INPUTREG_BASE_PROCESS + 0x0EU)
#define REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE  (INPUTREG_BASE_PROCESS + 0x10U)
#define REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL    (INPUTREG_BASE_PROCESS + 0x12U)
#define REG_HEIGHT_MEASUREMENT_CURRENT_REAL        (INPUTREG_BASE_PROCESS + 0x14U)
#define REG_PROCESS_BLOCK_END                      (INPUTREG_BASE_PROCESS + 0x16U)

/* 固定结果放在同一块内，可用一帧标准FC04读取 */
#define REG_SINGLE_POINT_MEAS_TEMP            (INPUTREG_BASE_FIXED_RESULTS + 0x00U)
#define REG_SINGLE_POINT_MEAS_DENSITY         (INPUTREG_BASE_FIXED_RESULTS + 0x02U)
#define REG_SINGLE_POINT_MEAS_TEMP_POS        (INPUTREG_BASE_FIXED_RESULTS + 0x04U)
#define REG_SINGLE_POINT_MEAS_STD_DENSITY     (INPUTREG_BASE_FIXED_RESULTS + 0x06U)
#define REG_SINGLE_POINT_MEAS_VCF20           (INPUTREG_BASE_FIXED_RESULTS + 0x08U)
#define REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY  (INPUTREG_BASE_FIXED_RESULTS + 0x0AU)

#define REG_SINGLE_POINT_MON_TEMP             (INPUTREG_BASE_FIXED_RESULTS + 0x20U)
#define REG_SINGLE_POINT_MON_DENSITY          (INPUTREG_BASE_FIXED_RESULTS + 0x22U)
#define REG_SINGLE_POINT_MON_TEMP_POS         (INPUTREG_BASE_FIXED_RESULTS + 0x24U)
#define REG_SINGLE_POINT_MON_STD_DENSITY      (INPUTREG_BASE_FIXED_RESULTS + 0x26U)
#define REG_SINGLE_POINT_MON_VCF20            (INPUTREG_BASE_FIXED_RESULTS + 0x28U)
#define REG_SINGLE_POINT_MON_WEIGHT_DENSITY   (INPUTREG_BASE_FIXED_RESULTS + 0x2AU)

#define REG_DENSITY_DIST_AVG_TEMP             (INPUTREG_BASE_FIXED_RESULTS + 0x40U)
#define REG_DENSITY_DIST_AVG_DENSITY          (INPUTREG_BASE_FIXED_RESULTS + 0x42U)
#define REG_DENSITY_DIST_AVG_STD_DENSITY      (INPUTREG_BASE_FIXED_RESULTS + 0x44U)
#define REG_DENSITY_DIST_AVG_VCF20            (INPUTREG_BASE_FIXED_RESULTS + 0x46U)
#define REG_DENSITY_DIST_AVG_WEIGHT_DENSITY   (INPUTREG_BASE_FIXED_RESULTS + 0x48U)
#define REG_DENSITY_DIST_MEAS_POINTS          (INPUTREG_BASE_FIXED_RESULTS + 0x4AU)
#define REG_DENSITY_DIST_OIL_LEVEL            (INPUTREG_BASE_FIXED_RESULTS + 0x4CU)
#define REG_DENSITY_DIST_PROFILE_COMPLETE_LATCHED (INPUTREG_BASE_FIXED_RESULTS + 0x4EU)
#define REG_DENSITY_DIST_PROFILE_COMPLETE_COUNTER (INPUTREG_BASE_FIXED_RESULTS + 0x50U)
#define REG_DENSITY_DIST_PROFILE_SOURCE       (INPUTREG_BASE_FIXED_RESULTS + 0x52U)
#define REG_DENSITY_DIST_PROFILE_BLOCKED_BY_PROCESS (INPUTREG_BASE_FIXED_RESULTS + 0x54U)
#define REG_DENSITY_DIST_PROFILE_TEMP_DEVIATION_ALARM (INPUTREG_BASE_FIXED_RESULTS + 0x56U)
#define REG_DENSITY_DIST_PROFILE_DENSITY_DEVIATION_ALARM (INPUTREG_BASE_FIXED_RESULTS + 0x58U)
#define REG_DENSITY_DIST_SI_PROFILE_PHASE     (INPUTREG_BASE_FIXED_RESULTS + 0x5AU)
#define REG_DENSITY_DIST_SI_PROFILE_CYCLE_COUNTER (INPUTREG_BASE_FIXED_RESULTS + 0x5CU)
#define REG_DENSITY_DIST_SI_PROFILE_PROGRESS_POINTS (INPUTREG_BASE_FIXED_RESULTS + 0x5EU)
#define REG_DENSITY_DIST_SUMMARY_REG_COUNT    32U
#define REG_FIXED_RESULT_BLOCK_END            (INPUTREG_BASE_FIXED_RESULTS + 0x60U)

/* AO运行状态：0x1400 */
#define REG_AO_OUTPUT_RUNTIME_BASE                    INPUTREG_BASE_AO_RUNTIME
#define REG_AO_OUTPUT_RUNTIME_TARGET_MA_X100          (REG_AO_OUTPUT_RUNTIME_BASE + 0x00U)
#define REG_AO_OUTPUT_RUNTIME_LAST_SENT_MA_X100       (REG_AO_OUTPUT_RUNTIME_BASE + 0x02U)
#define REG_AO_OUTPUT_RUNTIME_SOURCE                  (REG_AO_OUTPUT_RUNTIME_BASE + 0x04U)
#define REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_FLAGS      (REG_AO_OUTPUT_RUNTIME_BASE + 0x06U)
#define REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_REGISTER   (REG_AO_OUTPUT_RUNTIME_BASE + 0x08U)
#define REG_AO_OUTPUT_RUNTIME_LAST_ERROR_CODE         (REG_AO_OUTPUT_RUNTIME_BASE + 0x0AU)
#define REG_AO_OUTPUT_RUNTIME_UPDATE_COUNTER          (REG_AO_OUTPUT_RUNTIME_BASE + 0x0CU)
#define REG_AO_OUTPUT_RUNTIME_LAST_UPDATE_TICK        (REG_AO_OUTPUT_RUNTIME_BASE + 0x0EU)
#define REG_AO_OUTPUT_RUNTIME_LAST_SENT_TICK          (REG_AO_OUTPUT_RUNTIME_BASE + 0x10U)
#define REG_AO_OUTPUT_RUNTIME_PROCESS_VALUE_01MM      (REG_AO_OUTPUT_RUNTIME_BASE + 0x12U)
#define REG_AO_OUTPUT_RUNTIME_PERCENT_X100            (REG_AO_OUTPUT_RUNTIME_BASE + 0x14U)
#define REG_AO_OUTPUT_RUNTIME_PROCESS_VALID           (REG_AO_OUTPUT_RUNTIME_BASE + 0x16U)
#define REG_AO_OUTPUT_RUNTIME_SIMULATION_ENABLED      (REG_AO_OUTPUT_RUNTIME_BASE + 0x18U)
#define REG_AO_OUTPUT_RUNTIME_DAC_READBACK_MA_X100    (REG_AO_OUTPUT_RUNTIME_BASE + 0x1AU)
#define REG_AO_OUTPUT_RUNTIME_DAC_READBACK_VALID      (REG_AO_OUTPUT_RUNTIME_BASE + 0x1CU)
#define REG_AO_OUTPUT_RUNTIME_BLOCK_END               (REG_AO_OUTPUT_RUNTIME_BASE + 0x1EU)

/* 继电器运行状态：浮点数占2个寄存器，既有布尔状态各占1个寄存器 */
#define REG_RELAY_ALARM_RUNTIME_CHANNEL_COUNT HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT
#define REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT (REG_SIZE_FLOAT + 8U)
#define REG_RELAY_ALARM_RUNTIME_BASE INPUTREG_BASE_RELAY_RUNTIME
#define REG_RELAY_ALARM_RUNTIME_ALARM_VALUE(ch) \
    (REG_RELAY_ALARM_RUNTIME_BASE + ((ch) * REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT))
#define REG_RELAY_ALARM_RUNTIME_HH_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_ALARM_VALUE(ch) + REG_SIZE_FLOAT)
#define REG_RELAY_ALARM_RUNTIME_H_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_HH_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_HH_H_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_H_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_L_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_HH_H_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_LL_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_L_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_LL_L_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_LL_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_ANY_ERROR(ch) \
    (REG_RELAY_ALARM_RUNTIME_LL_L_ALARM(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_CLEAR_ALARM(ch) \
    (REG_RELAY_ALARM_RUNTIME_ANY_ERROR(ch) + 1U)
#define REG_RELAY_ALARM_RUNTIME_BLOCK_END \
    (REG_RELAY_ALARM_RUNTIME_BASE + \
     (REG_RELAY_ALARM_RUNTIME_CHANNEL_COUNT * REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT))

/* 无线运行状态：0x1600 */
#define REG_WIRELESS_PAIRING_RESULT                  (INPUTREG_BASE_WIRELESS + 0x00U)
#define REG_WIRELESS_PAIRING_MAC_VALID               (INPUTREG_BASE_WIRELESS + 0x02U)
#define REG_WIRELESS_PAIRING_MAC_HIGH                (INPUTREG_BASE_WIRELESS + 0x04U)
#define REG_WIRELESS_PAIRING_MAC_MID                 (INPUTREG_BASE_WIRELESS + 0x06U)
#define REG_WIRELESS_PAIRING_MAC_LOW                 (INPUTREG_BASE_WIRELESS + 0x08U)
#define REG_WIRELESS_PAIRING_ERROR_CODE              (INPUTREG_BASE_WIRELESS + 0x0AU)
#define REG_WIRELESS_PAIRING_UPDATE_COUNTER          (INPUTREG_BASE_WIRELESS + 0x0CU)
#define REG_WIRELESS_PAIRING_CONNECTION_VALID        (INPUTREG_BASE_WIRELESS + 0x0EU)
#define REG_WIRELESS_PAIRING_RSSI_VALID              (INPUTREG_BASE_WIRELESS + 0x10U)
#define REG_WIRELESS_PAIRING_RSSI                    (INPUTREG_BASE_WIRELESS + 0x12U)
#define REG_WIRELESS_PAIRING_CONNECTION_ERROR_CODE   (INPUTREG_BASE_WIRELESS + 0x14U)
#define REG_WIRELESS_PAIRING_RSSI_UPDATE_COUNTER     (INPUTREG_BASE_WIRELESS + 0x16U)
#define REG_WIRELESS_PAIRING_BLOCK_END               (INPUTREG_BASE_WIRELESS + 0x18U)

/* 200个密度点，每点6个UInt32字段，按点连续存放 */
#define REG_DENSITY_DIST_POINT_BASE INPUTREG_BASE_DENSITY_POINTS
#define REG_DENSITY_DIST_POINT_SIZE (6U * REG_SIZE_U32)
#define REG_DENSITY_POINT_TEMP(i) \
    (REG_DENSITY_DIST_POINT_BASE + ((uint16_t)(i) * REG_DENSITY_DIST_POINT_SIZE))
#define REG_DENSITY_POINT_DENSITY(i) (REG_DENSITY_POINT_TEMP(i) + 2U)
#define REG_DENSITY_POINT_TEMP_POS(i) (REG_DENSITY_POINT_TEMP(i) + 4U)
#define REG_DENSITY_POINT_STD_DENSITY(i) (REG_DENSITY_POINT_TEMP(i) + 6U)
#define REG_DENSITY_POINT_VCF20(i) (REG_DENSITY_POINT_TEMP(i) + 8U)
#define REG_DENSITY_POINT_WEIGHT_DENSITY(i) (REG_DENSITY_POINT_TEMP(i) + 10U)

#define REG_ENG INPUTREGISTER_AMOUNT

/* 判断[start, start + count)是否完整位于寄存器数组内 */
static inline bool LtdModbus_RangeWithin(uint16_t start, uint16_t count, uint16_t limit)
{
    return (count != 0U) && ((uint32_t)start + (uint32_t)count <= (uint32_t)limit);
}

/* 判断一个完整区间是否包含另一个完整区间 */
static inline bool LtdModbus_RangeContains(uint16_t start,
                                           uint16_t count,
                                           uint16_t target_start,
                                           uint16_t target_count)
{
    return ((uint32_t)target_start >= (uint32_t)start) &&
           ((uint32_t)target_start + (uint32_t)target_count <=
            (uint32_t)start + (uint32_t)count);
}

/* 判断单个CPU2保持寄存器地址是否位于可写块 */
static inline bool LtdModbus_HoldingRegisterIsWritable(uint16_t address)
{
    if (((address >= HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND) &&
         (address < HOLDREGISTER_DEVICEPARAM_PROTOCOL_VERSION)) ||
        ((address >= HOLDREGISTER_DEVICEPARAM_FAULT_AUTO_RECOVERY_RETRY_LIMIT) &&
         (address < HOLDREGISTER_DEVICEPARAM_FAULT_AUTO_RECOVERY_RETRY_LIMIT + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_MOTOR) &&
         (address < HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_OIL_HEIGHT) &&
         (address < HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_ENABLE + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_WATER) &&
         (address < HOLDREGISTER_DEVICEPARAM_WATER_LAG_CAP_THRESHOLD + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_CORRECTION) &&
         (address < HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_MEAS_CONFIG) &&
         (address < HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE + REG_STRIDE)) ||
        ((address >= HOLDREG_BASE_AO) &&
         (address < HOLDREGISTER_AO_SIMULATION_ENABLE + REG_STRIDE)) ||
        ((address >= HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE) &&
         (address < HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_END)) ||
        ((address >= HOLDREG_BASE_SI_WARTSILA) &&
         (address < HOLDREGISTER_DEVICEPARAM_SI_PROFILE_BOTTOM_DETECT_INTERVAL + REG_STRIDE)) ||
        ((address >= HOLDREGISTER_DEVICEPARAM_COMMAND) &&
         (address < HOLDREGISTER_DEVICEPARAM_COMMAND + REG_STRIDE))) {
        return true;
    }
    return false;
}

/* 按地址表与权限校验完整FC10写区间 */
static inline bool LtdModbus_HoldingWriteRangeIsValid(uint16_t start, uint16_t count)
{
    uint16_t offset;

    if (((start & 1U) != 0U) || ((count & 1U) != 0U) ||
        !LtdModbus_RangeWithin(start, count, HOLDREGISTER_AMOUNT)) {
        return false;
    }
    for (offset = 0U; offset < count; offset++) {
        if (!LtdModbus_HoldingRegisterIsWritable((uint16_t)(start + offset))) {
            return false;
        }
    }
    return true;
}

/* 判断地址是否属于4路清除锁存报警瞬时写槽 */
static inline bool LtdModbus_HoldingRegisterIsRelayClearAlarm(uint16_t address)
{
    uint16_t channel;

    for (channel = 0U; channel < HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT; channel++) {
        uint16_t clear_alarm = HOLDREGISTER_DEVICEPARAM_RELAY_CLEAR_ALARM(channel);
        if ((address >= clear_alarm) && (address < clear_alarm + REG_STRIDE)) {
            return true;
        }
    }
    return false;
}

/* 仅当整个FC10区间完全位于7个带参命令前置参数字段内时放行运行态写入。 */
static inline bool LtdModbus_HoldingWriteIsCommandArgumentOnly(uint16_t start,
                                                               uint16_t count)
{
    return (count != 0U) &&
           ((uint32_t)start >=
            (uint32_t)HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL) &&
           ((uint32_t)start + (uint32_t)count <=
            (uint32_t)HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE + REG_STRIDE);
}

/* 持久化写入排除命令、AO模拟开关和4路清除锁存报警瞬时写槽 */
static inline bool LtdModbus_HoldingWriteTouchesPersistent(uint16_t start, uint16_t count)
{
    uint16_t offset;

    for (offset = 0U; offset < count; offset++) {
        uint16_t address = (uint16_t)(start + offset);
        if (LtdModbus_HoldingRegisterIsWritable(address) &&
            !((address >= HOLDREGISTER_DEVICEPARAM_COMMAND) &&
              (address < HOLDREGISTER_DEVICEPARAM_COMMAND + REG_STRIDE)) &&
            !((address >= HOLDREGISTER_AO_SIMULATION_ENABLE) &&
              (address < HOLDREGISTER_AO_SIMULATION_ENABLE + REG_STRIDE)) &&
            !LtdModbus_HoldingRegisterIsRelayClearAlarm(address)) {
            return true;
        }
    }
    return false;
}

/* 这里只接受已经具备CPU2业务处理闭环的命令。 */
static inline bool LtdModbus_CommandIsImplemented(uint32_t command)
{
    switch (command) {
    case 0UL:
    case 1UL:
    case 2UL:
    case 3UL:
    case 4UL:
    case 5UL:
    case 6UL:
    case 7UL:
    case 8UL:
    case 9UL:
    case 10UL:
    case 11UL:
    case 12UL:
    case 13UL:
    case 14UL:
    case 15UL:
    case 16UL:
    case 20UL:
    case 100UL:
    case 101UL:
    case 102UL:
    case 103UL:
    case 104UL:
    case 105UL:
    case 106UL:
    case 107UL:
    case 108UL:
    case 109UL:
    case 110UL:
    case 113UL:
    case 114UL:
    case 116UL:
    case 117UL:
    case 118UL:
    case 119UL:
        return true;
    default:
        return false;
    }
}

#endif /* _STATEFORMODBUS_H */
