#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H

#include <stdint.h>

/* 功能码 */
#define FUNCTIONCODE_READ_HOLDREGISTER    0x03 /* Modbus 功能码：读保持寄存器。 */
#define FUNCTIONCODE_READ_INPUTREGISTER   0x04 /* Modbus 功能码：读输入寄存器。 */
#define FUNCTIONCODE_WRITE_MULREGISTER    0x10 /* Modbus 功能码：写多个保持寄存器。 */

/* 保持寄存器起始地址 */
#define HOLDREG_BASE_DEVICEPARAM 0x0000 /* 设备参数保持寄存器起始地址。 */

/* 约定：每个 32bit 参数占用 2 个保持寄存器 (16bit*2) */
#define REG_STRIDE 2 /* 32 位参数在 Modbus 中占用的 16 位寄存器跨度。 */
#define HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT 4 /* 继电器报警配置通道数量。 */
#define HOLDREGISTER_RELAY_ALARM_FIELD_COUNT   13 /* 每路继电器报警配置字段数量。 */
#define HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT (HOLDREGISTER_RELAY_ALARM_FIELD_COUNT * REG_STRIDE) /* 每路继电器报警配置占用寄存器数量。 */

/* ========================= 保持寄存器：DeviceParameters（对外） =========================
 * 注意：
 * 1) 本表严格按你当前 system_parameter.h 中 DeviceParameters 字段顺序排列。
 * 2) command 也占 2 个保持寄存器（与其他 u32 一致）。
 */
typedef enum
{
    /* -------- 指令 -------- */
    HOLDREGISTER_DEVICEPARAM_COMMAND                           = HOLDREG_BASE_DEVICEPARAM,

    /* -------- 基础参数 -------- */
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE                        = HOLDREGISTER_DEVICEPARAM_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSORID                          = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION           = HOLDREGISTER_DEVICEPARAM_SENSORID + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION                   = HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND          = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO              = HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT            = HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_PROTOCOL_VERSION                  = HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FAULT_AUTO_RECOVERY_RETRY_LIMIT   = HOLDREGISTER_DEVICEPARAM_PROTOCOL_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED2                         = HOLDREGISTER_DEVICEPARAM_FAULT_AUTO_RECOVERY_RETRY_LIMIT,
    HOLDREGISTER_DEVICEPARAM_RESERVED3                         = HOLDREGISTER_DEVICEPARAM_RESERVED2 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POSITION_SOURCE_AUTO_SWITCH        = HOLDREGISTER_DEVICEPARAM_RESERVED3 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_CURRENT                         = HOLDREGISTER_DEVICEPARAM_POSITION_SOURCE_AUTO_SWITCH + REG_STRIDE,

    /* -------- 电机与编码器参数 -------- */
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM    = HOLDREGISTER_DEVICEPARAM_MOTOR_CURRENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED                   = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM       = HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM                 = HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_POSITION_COUNT_MODE              = HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COUNT_FIRST_LOOP_CIRC      = HOLDREGISTER_DEVICEPARAM_POSITION_COUNT_MODE + REG_STRIDE,

    /* -------- 称重参数 -------- */
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT                      = HOLDREGISTER_DEVICEPARAM_MOTOR_COUNT_FIRST_LOOP_CIRC + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT          = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT          = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT                       = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT           = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT           = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO          = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO          = HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED8                         = HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED9                         = HOLDREGISTER_DEVICEPARAM_RESERVED8 + REG_STRIDE,

    /* -------- 零点测量 -------- */
    HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO       = HOLDREGISTER_DEVICEPARAM_RESERVED9 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE                = HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE       = HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE            = HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED10                        = HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED11                        = HOLDREGISTER_DEVICEPARAM_RESERVED10 + REG_STRIDE,

    /* -------- 液位测量 -------- */
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT                        = HOLDREGISTER_DEVICEPARAM_RESERVED11 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF       = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE                         = HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD                 = HOLDREGISTER_DEVICEPARAM_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD     = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD      = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY                        = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY                        = HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME          = HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY + REG_STRIDE,
    /* -------- 水位测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT                 = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE                  = HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE                   = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD               = HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_FIND_CAP_THRESHOLD              = HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE                   = HOLDREGISTER_DEVICEPARAM_WATER_FIND_CAP_THRESHOLD + REG_STRIDE,
	HOLDREGISTER_DEVICEPARAM_ZERO_CAP                        = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD                        = HOLDREGISTER_DEVICEPARAM_ZERO_CAP + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION            = HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD + REG_STRIDE,
    /* -------- 罐高/罐底测量 -------- */
    HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE                = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD            = HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD           = HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG           = HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION          = HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT                = HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT                = HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_ENABLE  = HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LAG_CAP_THRESHOLD                        = HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_ENABLE + REG_STRIDE,

    /* -------- 密度与温度修正 -------- */
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION                 = HOLDREGISTER_DEVICEPARAM_WATER_LAG_CAP_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION             = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED18                        = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED19                        = HOLDREGISTER_DEVICEPARAM_RESERVED18 + REG_STRIDE,

    /* -------- 分布/区间测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT          = HOLDREGISTER_DEVICEPARAM_RESERVED19 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT           = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY         = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER            = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE             = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT            = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE         = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT                    = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT                 = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME           = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT                 = HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT              = HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED20                        = HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED21                        = HOLDREGISTER_DEVICEPARAM_RESERVED20 + REG_STRIDE,

    /* -------- Wartsila 密度区间测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT      = HOLDREGISTER_DEVICEPARAM_RESERVED21 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT      = HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL         = HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE = HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_WARTSILA_BOTTOM_DETECT_INTERVAL   = HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_TANK_HEIGHT = HOLDREGISTER_DEVICEPARAM_WARTSILA_BOTTOM_DETECT_INTERVAL + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_AO_START_LEVEL                        = HOLDREGISTER_DEVICEPARAM_BOTTOM_ENCODER_CORRECTION_TANK_HEIGHT + REG_STRIDE,


    HOLDREGISTER_DEVICEPARAM_AO_END_LEVEL                        = HOLDREGISTER_DEVICEPARAM_AO_START_LEVEL + REG_STRIDE,

    /* -------- 4-20mA / 报警 AO -------- */
    HOLDREGISTER_DEVICEPARAM_AO_NORMAL_CURRENT_START_mA            = HOLDREGISTER_DEVICEPARAM_AO_END_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_NORMAL_CURRENT_END_mA              = HOLDREGISTER_DEVICEPARAM_AO_NORMAL_CURRENT_START_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_HIGH_ALARM_LEVEL                     = HOLDREGISTER_DEVICEPARAM_AO_NORMAL_CURRENT_END_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_LOW_ALARM_LEVEL                      = HOLDREGISTER_DEVICEPARAM_AO_HIGH_ALARM_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA                = HOLDREGISTER_DEVICEPARAM_AO_LOW_ALARM_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA                = HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA                 = HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA                  = HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA                  = HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_AO_OUTPUT_ENABLE                  = HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED26                        = HOLDREGISTER_DEVICEPARAM_AO_OUTPUT_ENABLE,
    HOLDREGISTER_DEVICEPARAM_RESERVED27                        = HOLDREGISTER_DEVICEPARAM_AO_OUTPUT_ENABLE + REG_STRIDE,

    /* -------- 指令参数 -------- */
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL               = HOLDREGISTER_DEVICEPARAM_RESERVED27 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL             = HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_TANK_HEIGHT             = HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION                  = HOLDREGISTER_DEVICEPARAM_CALIBRATE_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION               = HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL    = HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE            = HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED28                        = HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED29                        = HOLDREGISTER_DEVICEPARAM_RESERVED28 + REG_STRIDE,

    /* -------- Tape compensation -------- */
    HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL         = HOLDREGISTER_DEVICEPARAM_RESERVED29 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE        = HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT        = HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE      = HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED30                        = HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED31                        = HOLDREGISTER_DEVICEPARAM_RESERVED30 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED32                        = HOLDREGISTER_DEVICEPARAM_RESERVED31 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED33                        = HOLDREGISTER_DEVICEPARAM_RESERVED32 + REG_STRIDE,

    /* -------- 继电器报警输出配置（四路） -------- */
    HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE                  = HOLDREGISTER_DEVICEPARAM_RESERVED33 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_END                   = HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + (HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT),

    /* -------- 元信息与 CRC -------- */
    HOLDREGISTER_DEVICEPARAM_PARAM_VERSION                     = HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_END,
    HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE                       = HOLDREGISTER_DEVICEPARAM_PARAM_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAGIC                             = HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CRC                               = HOLDREGISTER_DEVICEPARAM_MAGIC + REG_STRIDE,

    /* 结束标志：下一个可用地址 */
    HOLEREGISTER_STOP                                          = HOLDREGISTER_DEVICEPARAM_CRC + REG_STRIDE
} HOLD;

#define HOLDREGISTER_DEVICEPARAM_RELAY_OPERATING_MODE(ch)   (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (0 * REG_STRIDE)) /* 继电器工作模式保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_DIGITAL_SOURCE(ch)   (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (1 * REG_STRIDE)) /* 继电器数字量来源保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_CONTACT_TYPE(ch)     (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (2 * REG_STRIDE)) /* 继电器触点类型保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_MODE(ch)       (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (3 * REG_STRIDE)) /* 继电器报警模式保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_ERROR_VALUE(ch)      (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (4 * REG_STRIDE)) /* 继电器错误值保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_SOURCE(ch)     (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (5 * REG_STRIDE)) /* 继电器报警来源保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_HH_ALARM_VALUE(ch)   (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (6 * REG_STRIDE)) /* 继电器高高报阈值保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_H_ALARM_VALUE(ch)    (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (7 * REG_STRIDE)) /* 继电器高报阈值保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_L_ALARM_VALUE(ch)    (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (8 * REG_STRIDE)) /* 继电器低报阈值保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_LL_ALARM_VALUE(ch)   (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (9 * REG_STRIDE)) /* 继电器低低报阈值保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_HYSTERESIS(ch) (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (10 * REG_STRIDE)) /* 继电器报警回差保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_DAMPING_FACTOR(ch)   (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (11 * REG_STRIDE)) /* 继电器阻尼系数保持寄存器地址。 */
#define HOLDREGISTER_DEVICEPARAM_RELAY_CLEAR_ALARM(ch)      (HOLDREGISTER_DEVICEPARAM_RELAY_ALARM_BASE + ((ch) * HOLDREGISTER_RELAY_ALARM_CHANNEL_REG_COUNT) + (12 * REG_STRIDE)) /* 继电器清除锁存报警保持寄存器地址。 */


/* ========================= 输入寄存器：MeasurementResult（对外） =========================
 * 约定：u32/i32/float 均占 2 个输入寄存器，保持对齐一致
 */
#define REG_SIZE_U32    2 /* uint32_t 数据占用的 16 位输入寄存器数量。 */
#define REG_SIZE_I32    2 /* int32_t 数据占用的 16 位输入寄存器数量。 */
#define REG_SIZE_FLOAT  2 /* float 数据占用的 16 位输入寄存器数量。 */
#define REG_SIZE_U8     2  /* 如后续有 u8，也按 2 个寄存器对齐 */

/* ==== DeviceStatus ==== */
#define REG_DEVICE_STATUS_WORK_MODE             (0) /* 工作模式输入寄存器偏移。 */
#define REG_DEVICE_STATUS_DEVICE_STATE          (REG_DEVICE_STATUS_WORK_MODE + REG_SIZE_U32) /* 设备状态输入寄存器偏移。 */
#define REG_DEVICE_STATUS_ERROR_CODE            (REG_DEVICE_STATUS_DEVICE_STATE + REG_SIZE_U32) /* 当前错误码输入寄存器偏移。 */
#define REG_DEVICE_STATUS_CURRENT_COMMAND       (REG_DEVICE_STATUS_ERROR_CODE + REG_SIZE_U32) /* 当前命令输入寄存器偏移。 */
#define REG_DEVICE_STATUS_ZERO_POINT_STATUS     (REG_DEVICE_STATUS_CURRENT_COMMAND + REG_SIZE_U32) /* 零点状态输入寄存器偏移。 */
#define REG_DEVICE_STATUS_PARAM_UPDATE_FLAG     (REG_DEVICE_STATUS_ZERO_POINT_STATUS + REG_SIZE_U32) /* 参数更新标志输入寄存器偏移。 */
/* SI7000 状态扩展：追加在 DeviceStatus 尾部，避免移动前面已有字段。 */
#define REG_DEVICE_STATUS_LOADING_UNLOADING_ACTIVE (REG_DEVICE_STATUS_PARAM_UPDATE_FLAG + REG_SIZE_U32) /* 装卸油活动标志输入寄存器偏移。 */
#define REG_DEVICE_STATUS_MANUAL_ALARM_INHIBIT (REG_DEVICE_STATUS_LOADING_UNLOADING_ACTIVE + REG_SIZE_U32) /* 手动报警抑制标志输入寄存器偏移。 */

/* ==== DebugData ==== */
#define REG_DEBUG_BASE                          (REG_DEVICE_STATUS_MANUAL_ALARM_INHIBIT + REG_SIZE_U32) /* 调试数据输入寄存器起始偏移。 */

#define REG_DEBUG_CURRENT_ENCODER               (REG_DEBUG_BASE + 0) /* 当前编码器值输入寄存器偏移。 */
#define REG_DEBUG_SENSOR_POSITION               (REG_DEBUG_CURRENT_ENCODER + REG_SIZE_I32) /* 传感器位置输入寄存器偏移。 */
#define REG_DEBUG_CABLE_LENGTH                  (REG_DEBUG_SENSOR_POSITION + REG_SIZE_I32) /* 尺带长度输入寄存器偏移。 */

/* 新增：motor_step / motor_distance（与你当前 DebugData 结构一致） */
#define REG_DEBUG_MOTOR_STEP                    (REG_DEBUG_CABLE_LENGTH + REG_SIZE_I32) /* 电机步数输入寄存器偏移。 */
#define REG_DEBUG_MOTOR_DISTANCE                (REG_DEBUG_MOTOR_STEP + REG_SIZE_I32) /* 电机距离输入寄存器偏移。 */

#define REG_DEBUG_FREQUENCY                     (REG_DEBUG_MOTOR_DISTANCE + REG_SIZE_I32) /* 当前频率输入寄存器偏移。 */
#define REG_DEBUG_TEMPERATURE                   (REG_DEBUG_FREQUENCY + REG_SIZE_U32) /* 当前温度输入寄存器偏移。 */
#define REG_DEBUG_AIR_FREQUENCY                 (REG_DEBUG_TEMPERATURE + REG_SIZE_U32) /* 空气频率输入寄存器偏移。 */
#define REG_DEBUG_CURRENT_AMPLITUDE             (REG_DEBUG_AIR_FREQUENCY + REG_SIZE_U32) /* 当前幅值输入寄存器偏移。 */
#define REG_DEBUG_WATER_CAPACITANCE_X10           (REG_DEBUG_CURRENT_AMPLITUDE + REG_SIZE_U32) /* 水位电容输入寄存器偏移，单位 0.1pF。 */

#define REG_DEBUG_CURRENT_WEIGHT                (REG_DEBUG_WATER_CAPACITANCE_X10 + REG_SIZE_U32) /* 当前称重值输入寄存器偏移。 */
#define REG_DEBUG_WEIGHT_PARAM                  (REG_DEBUG_CURRENT_WEIGHT + REG_SIZE_U32) /* 称重参数输入寄存器偏移。 */

#define REG_DEBUG_ANGLE_X                       (REG_DEBUG_WEIGHT_PARAM + REG_SIZE_U32) /* X 轴角度输入寄存器偏移。 */
#define REG_DEBUG_ANGLE_Y                       (REG_DEBUG_ANGLE_X + REG_SIZE_I32) /* Y 轴角度输入寄存器偏移。 */

#define REG_DEBUG_MOTOR_SPEED                   (REG_DEBUG_ANGLE_Y + REG_SIZE_I32) /* 电机速度输入寄存器偏移。 */
#define REG_DEBUG_MOTOR_STATE                   (REG_DEBUG_MOTOR_SPEED + REG_SIZE_U32) /* 电机状态输入寄存器偏移。 */

/* ==== OilMeasurement ==== */
#define REG_OIL_MEASUREMENT_OIL_LEVEL           (REG_DEBUG_MOTOR_STATE + REG_SIZE_U32) /* 油位测量结果输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_AIR_FREQUENCY       (REG_OIL_MEASUREMENT_OIL_LEVEL + REG_SIZE_U32) /* 油位测量空气频率输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_OIL_FREQUENCY       (REG_OIL_MEASUREMENT_AIR_FREQUENCY + REG_SIZE_U32) /* 油位测量油中频率输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY    (REG_OIL_MEASUREMENT_OIL_FREQUENCY + REG_SIZE_U32) /* 油位跟随目标频率输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_CURRENT_FREQUENCY   (REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY + REG_SIZE_U32) /* 油位测量当前频率输入寄存器偏移。 */
/* SI7000 液位状态扩展：跟随 OilMeasurement 尾部，CPU2/CPU3 顺序必须一致。 */
#define REG_OIL_MEASUREMENT_PROBE_AT_LIQUID_LEVEL (REG_OIL_MEASUREMENT_CURRENT_FREQUENCY + REG_SIZE_U32) /* 探头位于液面标志输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_LIQUID_STABLE      (REG_OIL_MEASUREMENT_PROBE_AT_LIQUID_LEVEL + REG_SIZE_U32) /* 液位稳定标志输入寄存器偏移。 */
#define REG_OIL_MEASUREMENT_MANUAL_LEVEL_UPDATE_INHIBIT (REG_OIL_MEASUREMENT_LIQUID_STABLE + REG_SIZE_U32) /* 手动液位更新抑制标志输入寄存器偏移。 */

/* ==== WaterMeasurement ==== */
#define REG_WATER_MEASUREMENT_WATER_LEVEL          (REG_OIL_MEASUREMENT_MANUAL_LEVEL_UPDATE_INHIBIT + REG_SIZE_U32) /* 水位测量结果输入寄存器偏移。 */
#define REG_WATER_MEASUREMENT_ZERO_CAPACITANCE     (REG_WATER_MEASUREMENT_WATER_LEVEL + REG_SIZE_U32) /* 水位零点电容输入寄存器偏移。 */
#define REG_WATER_MEASUREMENT_OIL_CAPACITANCE      (REG_WATER_MEASUREMENT_ZERO_CAPACITANCE + REG_SIZE_FLOAT) /* 油中电容输入寄存器偏移。 */
#define REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE  (REG_WATER_MEASUREMENT_OIL_CAPACITANCE + REG_SIZE_FLOAT) /* 当前水位电容输入寄存器偏移。 */

/* ==== ActualHeightMeasurement ==== */
#define REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL    (REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE + REG_SIZE_FLOAT) /* 罐高测量计算液位输入寄存器偏移。 */
#define REG_HEIGHT_MEASUREMENT_CURRENT_REAL        (REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL + REG_SIZE_U32) /* 罐高测量当前实高输入寄存器偏移。 */
/* 探底参考有效标志追加在实高测量尾部，供 CPU3 映射 SI7000 Bottom Reference。 */
#define REG_HEIGHT_MEASUREMENT_BOTTOM_REFERENCE_VALID (REG_HEIGHT_MEASUREMENT_CURRENT_REAL + REG_SIZE_U32) /* 罐底参考有效标志输入寄存器偏移。 */


/* ==== Single Point Measurement ==== */
#define REG_SINGLE_POINT_MEAS_TEMP                 (REG_HEIGHT_MEASUREMENT_BOTTOM_REFERENCE_VALID + REG_SIZE_U32) /* 单点测量温度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MEAS_DENSITY              (REG_SINGLE_POINT_MEAS_TEMP + REG_SIZE_U32) /* 单点测量密度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MEAS_TEMP_POS             (REG_SINGLE_POINT_MEAS_DENSITY + REG_SIZE_U32) /* 单点测量温度位置输入寄存器偏移。 */
#define REG_SINGLE_POINT_MEAS_STD_DENSITY          (REG_SINGLE_POINT_MEAS_TEMP_POS + REG_SIZE_U32) /* 单点测量标准密度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MEAS_VCF20                (REG_SINGLE_POINT_MEAS_STD_DENSITY + REG_SIZE_U32) /* 单点测量 VCF20 输入寄存器偏移。 */
#define REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY       (REG_SINGLE_POINT_MEAS_VCF20 + REG_SIZE_U32) /* 单点测量计重密度输入寄存器偏移。 */

/* ==== Single Point Monitoring ==== */
#define REG_SINGLE_POINT_MON_TEMP                  (REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY + REG_SIZE_U32) /* 单点监测温度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MON_DENSITY               (REG_SINGLE_POINT_MON_TEMP + REG_SIZE_U32) /* 单点监测密度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MON_TEMP_POS              (REG_SINGLE_POINT_MON_DENSITY + REG_SIZE_U32) /* 单点监测温度位置输入寄存器偏移。 */
#define REG_SINGLE_POINT_MON_STD_DENSITY           (REG_SINGLE_POINT_MON_TEMP_POS + REG_SIZE_U32) /* 单点监测标准密度输入寄存器偏移。 */
#define REG_SINGLE_POINT_MON_VCF20                 (REG_SINGLE_POINT_MON_STD_DENSITY + REG_SIZE_U32) /* 单点监测 VCF20 输入寄存器偏移。 */
#define REG_SINGLE_POINT_MON_WEIGHT_DENSITY        (REG_SINGLE_POINT_MON_VCF20 + REG_SIZE_U32) /* 单点监测计重密度输入寄存器偏移。 */

/* ==== Density Distribution Averages ==== */
#define REG_DENSITY_DIST_AVG_TEMP                  (REG_SINGLE_POINT_MON_WEIGHT_DENSITY + REG_SIZE_U32) /* 密度分布平均温度输入寄存器偏移。 */
#define REG_DENSITY_DIST_AVG_DENSITY               (REG_DENSITY_DIST_AVG_TEMP + REG_SIZE_U32) /* 密度分布平均密度输入寄存器偏移。 */
#define REG_DENSITY_DIST_AVG_STD_DENSITY           (REG_DENSITY_DIST_AVG_DENSITY + REG_SIZE_U32) /* 密度分布平均标准密度输入寄存器偏移。 */
#define REG_DENSITY_DIST_AVG_VCF20                 (REG_DENSITY_DIST_AVG_STD_DENSITY + REG_SIZE_U32) /* 密度分布平均 VCF20 输入寄存器偏移。 */
#define REG_DENSITY_DIST_AVG_WEIGHT_DENSITY        (REG_DENSITY_DIST_AVG_VCF20 + REG_SIZE_U32) /* 密度分布平均计重密度输入寄存器偏移。 */
#define REG_DENSITY_DIST_MEAS_POINTS               (REG_DENSITY_DIST_AVG_WEIGHT_DENSITY + REG_SIZE_U32) /* 密度分布已测点数输入寄存器偏移。 */
#define REG_DENSITY_DIST_OIL_LEVEL                 (REG_DENSITY_DIST_MEAS_POINTS + REG_SIZE_U32) /* 密度分布对应油位输入寄存器偏移。 */
/* SI7000 profile 状态扩展：必须位于点阵数据前，避免每个点的 6 个字段错位。 */
#define REG_DENSITY_DIST_PROFILE_COMPLETE_LATCHED (REG_DENSITY_DIST_OIL_LEVEL + REG_SIZE_U32) /* 密度分布完成锁存标志输入寄存器偏移。 */
#define REG_DENSITY_DIST_PROFILE_COMPLETE_COUNTER (REG_DENSITY_DIST_PROFILE_COMPLETE_LATCHED + REG_SIZE_U32) /* 密度分布完成计数器输入寄存器偏移。 */
#define REG_DENSITY_DIST_PROFILE_BLOCKED_BY_PROCESS (REG_DENSITY_DIST_PROFILE_COMPLETE_COUNTER + REG_SIZE_U32) /* 密度分布因工况被阻止标志输入寄存器偏移。 */
#define REG_DENSITY_DIST_PROFILE_TEMP_DEVIATION_ALARM (REG_DENSITY_DIST_PROFILE_BLOCKED_BY_PROCESS + REG_SIZE_U32) /* 密度分布温度偏差报警输入寄存器偏移。 */
#define REG_DENSITY_DIST_PROFILE_DENSITY_DEVIATION_ALARM (REG_DENSITY_DIST_PROFILE_TEMP_DEVIATION_ALARM + REG_SIZE_U32) /* 密度分布密度偏差报警输入寄存器偏移。 */

/* ==== Density Distribution Single Data ==== */
#define REG_DENSITY_DIST_POINT_BASE                (REG_DENSITY_DIST_PROFILE_DENSITY_DEVIATION_ALARM + REG_SIZE_U32) /* 密度分布点明细输入寄存器起始偏移。 */
#define REG_DENSITY_DIST_POINT_SIZE                (6 * REG_SIZE_U32) /* 每点 6 个 uint32 */

#define REG_DENSITY_POINT_TEMP(i)                  (REG_DENSITY_DIST_POINT_BASE + (i) * REG_DENSITY_DIST_POINT_SIZE) /* 密度分布点温度输入寄存器偏移。 */
#define REG_DENSITY_POINT_DENSITY(i)               (REG_DENSITY_POINT_TEMP(i) + REG_SIZE_U32) /* 密度分布点密度输入寄存器偏移。 */
#define REG_DENSITY_POINT_TEMP_POS(i)              (REG_DENSITY_POINT_TEMP(i) + 2 * REG_SIZE_U32) /* 密度分布点温度位置输入寄存器偏移。 */
#define REG_DENSITY_POINT_STD_DENSITY(i)           (REG_DENSITY_POINT_TEMP(i) + 3 * REG_SIZE_U32) /* 密度分布点标准密度输入寄存器偏移。 */
#define REG_DENSITY_POINT_VCF20(i)                 (REG_DENSITY_POINT_TEMP(i) + 4 * REG_SIZE_U32) /* 密度分布点 VCF20 输入寄存器偏移。 */
#define REG_DENSITY_POINT_WEIGHT_DENSITY(i)        (REG_DENSITY_POINT_TEMP(i) + 5 * REG_SIZE_U32) /* 密度分布点计重密度输入寄存器偏移。 */

/* ==== 无线滑环匹配状态 ==== */
#define REG_WIRELESS_PAIRING_RESULT          (REG_DENSITY_DIST_POINT_BASE + MAX_MEASUREMENT_POINTS * REG_DENSITY_DIST_POINT_SIZE) /* 无线滑环配对结果输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_MAC_VALID       (REG_WIRELESS_PAIRING_RESULT + REG_SIZE_U32) /* 无线滑环 MAC 有效标志输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_MAC_HIGH        (REG_WIRELESS_PAIRING_MAC_VALID + REG_SIZE_U32) /* 无线滑环 MAC 高位输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_MAC_MID         (REG_WIRELESS_PAIRING_MAC_HIGH + REG_SIZE_U32) /* 无线滑环 MAC 中位输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_MAC_LOW         (REG_WIRELESS_PAIRING_MAC_MID + REG_SIZE_U32) /* 无线滑环 MAC 低位输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_ERROR_CODE      (REG_WIRELESS_PAIRING_MAC_LOW + REG_SIZE_U32) /* 无线滑环配对错误码输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_UPDATE_COUNTER  (REG_WIRELESS_PAIRING_ERROR_CODE + REG_SIZE_U32) /* 无线滑环配对更新计数器输入寄存器偏移。 */

/* ==== 继电器报警输出运行态 ==== */
#define REG_RELAY_ALARM_RUNTIME_CHANNEL_COUNT     HOLDREGISTER_RELAY_ALARM_CHANNEL_COUNT /* 继电器报警运行态通道数量。 */
#define REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT (REG_SIZE_FLOAT + 8U) /* 每路继电器报警运行态占用寄存器数量。 */
#define REG_RELAY_ALARM_RUNTIME_BASE              (REG_WIRELESS_PAIRING_UPDATE_COUNTER + REG_SIZE_U32) /* 继电器报警运行态输入寄存器起始偏移。 */
#define REG_RELAY_ALARM_RUNTIME_ALARM_VALUE(ch)   (REG_RELAY_ALARM_RUNTIME_BASE + ((ch) * REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT)) /* 继电器当前报警值输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_HH_ALARM(ch)      (REG_RELAY_ALARM_RUNTIME_ALARM_VALUE(ch) + REG_SIZE_FLOAT) /* 继电器高高报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_H_ALARM(ch)       (REG_RELAY_ALARM_RUNTIME_HH_ALARM(ch) + 1U) /* 继电器高报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_HH_H_ALARM(ch)    (REG_RELAY_ALARM_RUNTIME_H_ALARM(ch) + 1U) /* 继电器高高报或高报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_L_ALARM(ch)       (REG_RELAY_ALARM_RUNTIME_HH_H_ALARM(ch) + 1U) /* 继电器低报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_LL_ALARM(ch)      (REG_RELAY_ALARM_RUNTIME_L_ALARM(ch) + 1U) /* 继电器低低报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_LL_L_ALARM(ch)    (REG_RELAY_ALARM_RUNTIME_LL_ALARM(ch) + 1U) /* 继电器低低报或低报状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_ANY_ERROR(ch)     (REG_RELAY_ALARM_RUNTIME_LL_L_ALARM(ch) + 1U) /* 继电器任意报警状态输入寄存器偏移。 */
#define REG_RELAY_ALARM_RUNTIME_CLEAR_ALARM(ch)   (REG_RELAY_ALARM_RUNTIME_ANY_ERROR(ch) + 1U) /* 继电器清除报警状态输入寄存器偏移。 */

/* ==== 无线 RSSI 运行态 ==== */
#define REG_WIRELESS_PAIRING_CONNECTION_VALID      (REG_RELAY_ALARM_RUNTIME_BASE + (REG_RELAY_ALARM_RUNTIME_CHANNEL_COUNT * REG_RELAY_ALARM_RUNTIME_CHANNEL_REG_COUNT)) /* 无线滑环连接有效标志输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_RSSI_VALID            (REG_WIRELESS_PAIRING_CONNECTION_VALID + REG_SIZE_U32) /* 无线滑环 RSSI 有效标志输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_RSSI                  (REG_WIRELESS_PAIRING_RSSI_VALID + REG_SIZE_U32) /* 无线滑环 RSSI 输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_CONNECTION_ERROR_CODE (REG_WIRELESS_PAIRING_RSSI + REG_SIZE_I32) /* 无线滑环连接错误码输入寄存器偏移。 */
#define REG_WIRELESS_PAIRING_RSSI_UPDATE_COUNTER   (REG_WIRELESS_PAIRING_CONNECTION_ERROR_CODE + REG_SIZE_U32) /* 无线滑环 RSSI 更新计数器输入寄存器偏移。 */

/* ==== AO 输出运行态 ==== */
#define REG_AO_OUTPUT_RUNTIME_REG_COUNT             (9U * REG_SIZE_U32) /* 模拟量输出运行态输入寄存器总长度。 */
#define REG_AO_OUTPUT_RUNTIME_BASE                  (REG_WIRELESS_PAIRING_RSSI_UPDATE_COUNTER + REG_SIZE_U32) /* 模拟量输出运行态输入寄存器起始偏移。 */
#define REG_AO_OUTPUT_RUNTIME_TARGET_MA_X100        (REG_AO_OUTPUT_RUNTIME_BASE) /* 模拟量输出目标电流输入寄存器偏移，单位 0.01mA。 */
#define REG_AO_OUTPUT_RUNTIME_LAST_SENT_MA_X100     (REG_AO_OUTPUT_RUNTIME_TARGET_MA_X100 + REG_SIZE_U32) /* 模拟量输出最后下发电流输入寄存器偏移，单位 0.01mA。 */
#define REG_AO_OUTPUT_RUNTIME_SOURCE                (REG_AO_OUTPUT_RUNTIME_LAST_SENT_MA_X100 + REG_SIZE_U32) /* 模拟量输出来源输入寄存器偏移。 */
#define REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_FLAGS    (REG_AO_OUTPUT_RUNTIME_SOURCE + REG_SIZE_U32) /* 模拟量输出驱动故障标志输入寄存器偏移。 */
#define REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_REGISTER (REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_FLAGS + REG_SIZE_U32) /* 模拟量输出驱动故障寄存器回读值偏移。 */
#define REG_AO_OUTPUT_RUNTIME_LAST_ERROR_CODE       (REG_AO_OUTPUT_RUNTIME_DRIVER_FAULT_REGISTER + REG_SIZE_U32) /* 模拟量输出最后错误码输入寄存器偏移。 */
#define REG_AO_OUTPUT_RUNTIME_UPDATE_COUNTER        (REG_AO_OUTPUT_RUNTIME_LAST_ERROR_CODE + REG_SIZE_U32) /* 模拟量输出状态更新计数器输入寄存器偏移。 */
#define REG_AO_OUTPUT_RUNTIME_LAST_UPDATE_TICK      (REG_AO_OUTPUT_RUNTIME_UPDATE_COUNTER + REG_SIZE_U32) /* 模拟量输出最后状态更新时间输入寄存器偏移。 */
#define REG_AO_OUTPUT_RUNTIME_LAST_SENT_TICK        (REG_AO_OUTPUT_RUNTIME_LAST_UPDATE_TICK + REG_SIZE_U32) /* 模拟量输出最后下发时间输入寄存器偏移。 */

/* ==== 输入寄存器最终数量 ==== */
#define REG_ENG                                  (REG_AO_OUTPUT_RUNTIME_BASE + REG_AO_OUTPUT_RUNTIME_REG_COUNT) /* 输入寄存器偏移：REG 结束地址。 */
#define INPUTREGISTER_AMOUNT                     (REG_ENG) /* 输入寄存器总数量。 */

/* 其他状态码（保留你原定义） */
#define ALARMSTATE_NONE 0 /* 报警状态：无报警。 */
#define ALARMSTATE_LOW  1 /* 报警状态：低报。 */
#define ALARMSTATE_HIGH 2 /* 报警状态：高报。 */

#define AVETEMPERATURESTATE_UNVALID 0 /* 平均温度状态：无效。 */
#define AVETEMPERATURESTATE_VALID   1 /* 平均温度状态：有效。 */

#define AVERAGEDENSITY_UNVALID      0 /* 平均密度状态：无效。 */
#define AVERAGEDENSITY_VALID        1 /* 平均密度状态：有效。 */

#define WATER_UNVALID               0 /* 水位结果状态：无效。 */
#define WATER_VALID                 1 /* 水位结果状态：有效。 */

#endif
