#ifndef __DISPLAY_TANKOPERA_H
#define __DISPLAY_TANKOPERA_H 
#include "main.h"

#define FIXPASSWORD         1009
extern bool flag_SendCommand;

struct KeyMenu {
	void (*back_opera)();
	void (*up_opera)();
	void (*down_opera)();
	void (*sure_opera)();
	int keyauthority;           //按键权限
	void (*execute_opera)();    //执行本次操作
};
extern struct KeyMenu keymenu[];
/*菜单索引号*/
typedef enum {
	KEYNUM_IF_ENTER_MAINMENU = 0,  // 是否进入主菜单
	KEYNUM_MAINMENU = 1,  // 主菜单
	KEYNUM_IF_EXIT_MAINMENU = 2,  // 是否退出主菜单
	KEYNUM_MEASURE_MAINMENU = 3,  // 普通测量指令主菜单
	KEYNUM_MENU_PARACFG_MAIN = 4,  // 参数配置主菜单
	KEYNUM_MENU_PARACFG_BASE = 5,  // 菜单 - 基础参数
	KEYNUM_MENU_CMD_MAIN = 6,  // 菜单 - 维护调试指令
	KEYNUM_IFSENDCMD = 7,  // 是否下发指令或参数
	KEYNUM_INPUTCMDPARA = 8,  // 请输入参数值(带参指令中的)
	KEYNUM_DISPLAY_PARA = 9,  // 参数显示(读写类参数中的)
	KEYNUM_MAGNETIC = 10, // 菜单 - 磁通量参数
	KEYNUM_WORDSELECT = 11, // 隐藏信息选择
	KEYNUM_SCREEN = 12, // 菜单 - 界面显示类参数
	KEYNUM_SOURCE = 13, // 菜单 - 数据源
	KEYNUM_MENU_PARACFG_DEBUG_BASIC = 14, // 维护参数 - 基础参数
	KEYNUM_MENU_PARACFG_DEBUG_SYNTH = 15, // 维护参数 - 综合测量参数
	KEYNUM_MENU_PARACFG_DEBUG_SPREAD = 16, // 维护参数 - 分布测量参数
	KEYNUM_MENU_PARACFG_DEBUG_CORRECT = 17, // 维护参数 - 修正参数
	KEYNUM_MENU_PARACFG_DEBUG_REALHIGH = 18, // 维护参数 - 实高测量
	KEYNUM_MENU_PARACFG_DEBUG_LIQUIDLEVEL,
	KEYNUM_MENU_PARACFG_DEBUG_WATERLEVEL,
	KEYNUM_MENU_PARACFG_DEBUG_ALARM_DO,
	KEYNUM_MENU_PARACFG_DEBUG_AO,
	KEYNUM_MENU_LANGUAGE , 		// 界面显示 - 语言
	KEYNUM_END
} keymenuNumber;
typedef enum {
	COM_NUM_NOOPERA,                //无指令 - 且无特殊跳转

	COM_NUM_NOPARACMD_START, /* 不带参线圈指令类 - 开始*/

	COM_NUM_NOPARACMD_NORMAL_START, /* 指令 - 普通 - 开始 */
	COM_NUM_SET_WORKPATTERN,	//	设置工作模式
	COM_NUM_BACK_ZERO,	//	返回零点
	COM_NUM_FIND_ZERO,	//	标定零点
	COM_NUM_SPREADPOINTS_AI,	//	自动分布测量
	COM_NUM_FIND_OIL,	//	寻找液位
	COM_NUM_FIND_WATER,	//	寻找水位
	COM_NUM_FIND_BOTTOM,	//	寻找罐底
	COM_NUM_SYNTHETIC,	//	综合测量
	COM_NUM_METER_DENSITY,	//	每米测量
	COM_NUM_INTERVAL_DENSITY,	//	区间测量
	COM_NUM_SET_EMPTY_WEIGHT,//    设置空载称重
	COM_NUM_SET_FULL_WEIGHT,    // 设置满载称重
	COM_NUM_RESTOR_EFACTORYSETTING,   // 恢复出厂设置
	COM_NUM_NOPARACMD_NORMAL_STOP, /* 指令 - 普通 - 结束 */

	COM_NUM_DEBUGCMD_START,	//调试模式指令
//	COM_NUM_READPARAMETER,	//	读部件参数
//	COM_NUM_FORCE_ZERO,	//	置零点
	COM_NUM_DEBUGCMD_STOP,	//调试模式指令

	COM_NUM_UNLOCK_START,
//	COM_NUM_BACKUP_FILE,          // 备份配置文件
//	COM_NUM_RESTORY_FILE,         // 恢复配置文件
	COM_NUM_UNLOCK_STOP,

	COM_NUM_NOPARACMD_END, /* 不带参线圈指令类 - 结束*/

	COM_NUM_ONEPARACMD_START, /*工作模式带一个参数线圈指令类 - 开始*/
	COM_NUM_SINGLE_POINT,        // 单点测量
	COM_NUM_SP_TEST,           // 单点监测
	COM_NUM_SPREADPOINTS,        // 分布测量
	COM_NUM_ONEPARACMD_END, /*工作模式带一个参数线圈指令类 - 结束*/

	COM_NUM_ONEPARA_DEBUGCMD_START, /*调试模式带一个参数线圈指令类 - 开始*/
	COM_NUM_CAL_OIL,	//	液位标定
	COM_NUM_RUNUP,	//	向上运行
	COM_NUM_RUNDOWN,	//	向下运行
	COM_NUM_SET_ZEROCIRCLE,	//	设置零点圈数
	COM_NUM_SET_ZEROANGLE,	//	设置零点角度
	COM_NUM_CORRECTION_OIL,	//	修正液位
	COM_NUM_NOPARA_DEBUGCMD_END, /*调试模式带一个参数线圈指令类 - 结束*/

	COM_NUM_PARACONFIG_START, /* 参数配置类 - 开始 */
	COM_NUM_PARA_LOCAL_START, /* 本机参数 - 开始 */

	COM_NUM_PARA_LOCAL_LEDVERSION,      //屏幕程序版本
	COM_NUM_PARA_LANG,                  //语言

	COM_NUM_SOURCE_START,               //数据源相关
	COM_NUM_SCREEN_SOURCE_OIL,
	COM_NUM_SCREEN_SOURCE_WATER,
	COM_NUM_SCREEN_SOURCE_D,
	COM_NUM_SCREEN_SOURCE_T,
	COM_NUM_SCREEN_INPUT_OIL,
	COM_NUM_SCREEN_INPUT_WATER,
	COM_NUM_SCREEN_INPUT_D,
	COM_NUM_SCREEN_INPUT_D_SWITCH,
	COM_NUM_SCREEN_INPUT_T,
	COM_NUM_SOURCE_STOP,

	COM_NUM_SCREEN_STR,                 //界面显示类
	COM_NUM_SCREEN_DECIMAL,
	COM_NUM_SCREEN_PASSWARD,
	COM_NUM_SCREEN_OFF,
	COM_NUM_SCREEN_STP,

	COM_NUM_PARA_LOCAL_STOP, /* 本机参数 - 结束 */

	COM_NUM_PARA_DEBUG_START, /*基础参数 - 开始 - 从此处往下都是CPU2存储的参数了*/

	COM_NUM_DEVICEPARAM_COMMAND,

	COM_NUM_DEVICEPARAM_TANKHEIGHT,
	COM_NUM_DEVICEPARAM_BLINDZONE,
	COM_NUM_DEVICEPARAM_WATER_BLINDZONE,
	COM_NUM_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM,
	COM_NUM_DEVICEPARAM_SENSORTYPE,
	COM_NUM_DEVICEPARAM_SENSORID,
	COM_NUM_DEVICEPARAM_SOFTWAREVERSION,

	/* 称重参数 */
	COM_NUM_DEVICEPARAM_EMPTY_WEIGHT,
	COM_NUM_DEVICEPARAM_FULL_WEIGHT,
	COM_NUM_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO,
	COM_NUM_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO,
	COM_NUM_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT,
	COM_NUM_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT,
	COM_NUM_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT,
	COM_NUM_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT,
	COM_NUM_DEVICEPARAM_FINDZERO_DOWN_DISTANCE,

	/* 指令参数 */
	COM_NUM_DEVICEPARAM_CALIBRATE_OIL_LEVEL,
	COM_NUM_DEVICEPARAM_CALIBRATE_WATER_LEVEL,
	COM_NUM_DEVICEPARAM_SP_MEAS_POSITION,
	COM_NUM_DEVICEPARAM_SP_MONITOR_POSITION,
	COM_NUM_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL,
	COM_NUM_DEVICEPARAM_MOTOR_COMMAND_DISTANCE,

	/* 密度温度修正 */
	COM_NUM_DEVICEPARAM_DENSITYCORRECTION,
	COM_NUM_DEVICEPARAM_TEMPERATURECORRECTION,

	/* 分布测量参数 */
	COM_NUM_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT,
	COM_NUM_DEVICEPARAM_REQUIREWATERMEASUREMENT,
	COM_NUM_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY,
	COM_NUM_DEVICEPARAM_SPREADMEASUREMENTORDER,
	COM_NUM_DEVICEPARAM_SPREADMEASUREMENTMODE,
	COM_NUM_DEVICEPARAM_SPREADMEASUREMENTCOUNT,
	COM_NUM_DEVICEPARAM_SPREADMEASUREMENTDISTANCE,
	COM_NUM_DEVICEPARAM_SPREADTOPLIMIT,
	COM_NUM_DEVICEPARAM_SPREADBOTTOMLIMIT,
	COM_NUM_DEVICEPARAM_SPREAD_POINT_HOVER_TIME,

	/* 水位测量参数 */
	COM_NUM_DEVICEPARAM_WATERLEVELCORRECTION,
	COM_NUM_DEVICEPARAM_MAXDOWNDISTANCE,

	/* 实高测量 */
	COM_NUM_DEVICEPARAM_REFRESHTANKHEIGHTFLAG,
	COM_NUM_DEVICEPARAM_MAXTANKHEIGHTDEVIATION,
	COM_NUM_DEVICEPARAM_INITIALTANKHEIGHT,
	COM_NUM_DEVICEPARAM_CURRENTTANKHEIGHT,

	/* 液位测量 */
	COM_NUM_DEVICEPARAM_OILLEVELTHRESHOLD,
	COM_NUM_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD,

	/* 报警（DO） */
	COM_NUM_DEVICEPARAM_ALARM_HIGH_DO,
	COM_NUM_DEVICEPARAM_ALARM_LOW_DO,
	COM_NUM_DEVICEPARAM_THIRD_STATE_THRESHOLD,

	/* 4–20mA 输出与报警（AO） */
	COM_NUM_DEVICEPARAM_CURRENT_RANGE_START_mA,
	COM_NUM_DEVICEPARAM_CURRENT_RANGE_END_mA,
	COM_NUM_DEVICEPARAM_ALARM_HIGH_AO,
	COM_NUM_DEVICEPARAM_ALARM_LOW_AO,
	COM_NUM_DEVICEPARAM_INITIAL_CURRENT_mA,
	COM_NUM_DEVICEPARAM_AO_HIGH_CURRENT_mA,
	COM_NUM_DEVICEPARAM_AO_LOW_CURRENT_mA,
	COM_NUM_DEVICEPARAM_FAULT_CURRENT_mA,
	COM_NUM_DEVICEPARAM_DEBUG_CURRENT_mA,

	/* CRC */
	COM_NUM_DEVICEPARAM_CRC,

	COM_NUM_PARA_DEBUG_END, /*基础参数 - 结束*/

	COM_NUM_PARACONFIG_END, /* 参数配置类 - 结束 */

	COM_NUM_PASSWORD_START, /* 密码类 - 开始 */
	COM_NUM_PASSWORD_ENTER_PARA,                //进入参数配置的密码
	COM_NUM_PASSWORD_ENTER_CMD,                 //进入调试指令的密码
	COM_NUM_PASSWORD_END, /* 密码类 - 结束 */

	COM_NUM_END,
} OperatingNumber;

struct ParaContent {
	int val;
	int points;
	uint8_t *unit;
	uint8_t bits;
};
struct MenuData {
	uint8_t *operaName;
	int operaNum;
	void (*sureopera)();
	int rorw;
	uint8_t *operaName2;
};
/*指令中读写操作*/
typedef enum {
	COMMANE_NORW = 0, COMMAND_READ = 1, COMMAND_WRITE = 2,
} CommandOpera;

extern struct ParaContent now_Para_CT;

void KeyProcess(uint8_t keypress);
void useKey(void);
void exitTankOpera(void);
uint8_t* ret_arr_word(void);
void ClearPageNum(void);

#endif

