#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H


/*功能码*/
#define FUNCTIONCODE_READ_HOLDREGISTER    0x03
#define FUNCTIONCODE_READ_INPUTREGISTER   0x04
#define FUNCTIONCODE_WRITE_MULREGISTER    0x10

/* 保持寄存器地址 */
#define HOLDREG_BASE_DEVICEPARAM 0x00

/* 约定: 每个 32 位参数占用 2 个保持寄存器 (16bit * 2) */
#define REG_STRIDE 2

typedef enum
{
    /* -------- 指令 -------- */
    HOLDREGISTER_DEVICEPARAM_COMMAND                           = HOLDREG_BASE_DEVICEPARAM,

    /* -------- 基础参数 -------- */
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE                        = HOLDREGISTER_DEVICEPARAM_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSORID                          = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION           = HOLDREGISTER_DEVICEPARAM_SENSORID + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION                   = HOLDREGISTER_DEVICEPARAM_SENSOR_SOFTWARE_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND          = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO              = HOLDREGISTER_DEVICEPARAM_POWER_ON_DEFAULT_COMMAND + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT            = HOLDREGISTER_DEVICEPARAM_ERROR_AUTO_BACK_ZERO + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED1                         = HOLDREGISTER_DEVICEPARAM_ERROR_STOP_MEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED2                         = HOLDREGISTER_DEVICEPARAM_RESERVED1 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED3                         = HOLDREGISTER_DEVICEPARAM_RESERVED2 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED4                         = HOLDREGISTER_DEVICEPARAM_RESERVED3 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED5                         = HOLDREGISTER_DEVICEPARAM_RESERVED4 + REG_STRIDE,

    /* -------- 电机与编码器参数 -------- */
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM    = HOLDREGISTER_DEVICEPARAM_RESERVED5 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED                   = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM       = HOLDREGISTER_DEVICEPARAM_MAX_MOTOR_SPEED + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM                 = HOLDREGISTER_DEVICEPARAM_FIRST_LOOP_CIRCUMFERENCE_MM + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED6                         = HOLDREGISTER_DEVICEPARAM_TAPE_THICKNESS_MM + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED7                         = HOLDREGISTER_DEVICEPARAM_RESERVED6 + REG_STRIDE,

    /* -------- 称重参数 -------- */
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT                      = HOLDREGISTER_DEVICEPARAM_RESERVED7 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT          = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT          = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT                       = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT           = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT           = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_UPPER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO          = HOLDREGISTER_DEVICEPARAM_FULL_WEIGHT_LOWER_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO          = HOLDREGISTER_DEVICEPARAM_WEIGHT_UPPER_LIMIT_RATIO + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED8                         = HOLDREGISTER_DEVICEPARAM_WEIGHT_LOWER_LIMIT_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED9                         = HOLDREGISTER_DEVICEPARAM_RESERVED8 + REG_STRIDE,

    /* -------- 零点测量 -------- */
    HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO       = HOLDREGISTER_DEVICEPARAM_RESERVED9 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE                = HOLDREGISTER_DEVICEPARAM_ZERO_WEIGHT_THRESHOLD_RATIO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE       = HOLDREGISTER_DEVICEPARAM_WEIGHT_IGNORE_ZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE            = HOLDREGISTER_DEVICEPARAM_MAX_ZERO_DEVIATION_DISTANCE + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED10                        = HOLDREGISTER_DEVICEPARAM_FINDZERO_DOWN_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED11                        = HOLDREGISTER_DEVICEPARAM_RESERVED10 + REG_STRIDE,

    /* -------- 液位测量 -------- */
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT                        = HOLDREGISTER_DEVICEPARAM_RESERVED11 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF       = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE                         = HOLDREGISTER_DEVICEPARAM_LIQUID_SENSOR_DISTANCE_DIFF + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD                 = HOLDREGISTER_DEVICEPARAM_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD     = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD      = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_THRESHOLD + REG_STRIDE,

	HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY                = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY                  = HOLDREGISTER_DEVICEPARAM_OILLEVEL_FREQUENCY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME          = HOLDREGISTER_DEVICEPARAM_OILLEVEL_DENSITY + REG_STRIDE,
    /* -------- 水位测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT                 = HOLDREGISTER_DEVICEPARAM_OILLEVEL_HYSTERESIS_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE                  = HOLDREGISTER_DEVICEPARAM_WATER_TANK_HEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE                   = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD               = HOLDREGISTER_DEVICEPARAM_WATER_BLINDZONE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_CAP_HYSTERESIS              = HOLDREGISTER_DEVICEPARAM_WATER_CAP_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE                   = HOLDREGISTER_DEVICEPARAM_WATER_CAP_HYSTERESIS + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_ZERO_CAP                          = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD                        = HOLDREGISTER_DEVICEPARAM_ZERO_CAP + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION            = HOLDREGISTER_DEVICEPARAM_WATER_STABLE_THRESHOLD + REG_STRIDE,
    /* -------- 罐高/罐底测量 -------- */
    HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE                = HOLDREGISTER_DEVICEPARAM_WATER_LEVEL_CORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD            = HOLDREGISTER_DEVICEPARAM_BOTTOM_DETECT_MODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD           = HOLDREGISTER_DEVICEPARAM_BOTTOM_ANGLE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG           = HOLDREGISTER_DEVICEPARAM_BOTTOM_WEIGHT_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION          = HOLDREGISTER_DEVICEPARAM_REFRESH_TANKHEIGHT_FLAG + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT                = HOLDREGISTER_DEVICEPARAM_MAX_TANKHEIGHT_DEVIATION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT                = HOLDREGISTER_DEVICEPARAM_INITIAL_TANKHEIGHT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED16                        = HOLDREGISTER_DEVICEPARAM_CURRENT_TANKHEIGHT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED17                        = HOLDREGISTER_DEVICEPARAM_RESERVED16 + REG_STRIDE,

    /* -------- 密度与温度修正 -------- */
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION                 = HOLDREGISTER_DEVICEPARAM_RESERVED17 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION             = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED18                        = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED19                        = HOLDREGISTER_DEVICEPARAM_RESERVED18 + REG_STRIDE,

    /* -------- 分布/区间测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT          = HOLDREGISTER_DEVICEPARAM_RESERVED19 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT           = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY         = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER            = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE             = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT            = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE         = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT                    = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT                 = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME           = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT                 = HOLDREGISTER_DEVICEPARAM_SPREAD_POINT_HOVER_TIME + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT              = HOLDREGISTER_DEVICEPARAM_INTERVAL_TOPLIMIT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED20                        = HOLDREGISTER_DEVICEPARAM_INTERVAL_BOTTOMLIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED21                        = HOLDREGISTER_DEVICEPARAM_RESERVED20 + REG_STRIDE,

    /* -------- Wartsila 密度区间测量参数 -------- */
    HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT      = HOLDREGISTER_DEVICEPARAM_RESERVED21 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT      = HOLDREGISTER_DEVICEPARAM_WARTSILA_UPPER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL         = HOLDREGISTER_DEVICEPARAM_WARTSILA_LOWER_DENSITY_LIMIT + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE = HOLDREGISTER_DEVICEPARAM_WARTSILA_DENSITY_INTERVAL + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED22                        = HOLDREGISTER_DEVICEPARAM_WARTSILA_MAX_HEIGHT_ABOVE_SURFACE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED23                        = HOLDREGISTER_DEVICEPARAM_RESERVED22 + REG_STRIDE,

    /* -------- 继电器报警 DO -------- */
    HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_DO                     = HOLDREGISTER_DEVICEPARAM_RESERVED23 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_LOW_DO                      = HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_DO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_THIRD_STATE_THRESHOLD             = HOLDREGISTER_DEVICEPARAM_ALARM_LOW_DO + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED24                        = HOLDREGISTER_DEVICEPARAM_THIRD_STATE_THRESHOLD + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED25                        = HOLDREGISTER_DEVICEPARAM_RESERVED24 + REG_STRIDE,

    /* -------- 4-20mA / 报警 AO -------- */
    HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_START_mA            = HOLDREGISTER_DEVICEPARAM_RESERVED25 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_END_mA              = HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_START_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_AO                     = HOLDREGISTER_DEVICEPARAM_CURRENT_RANGE_END_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_ALARM_LOW_AO                      = HOLDREGISTER_DEVICEPARAM_ALARM_HIGH_AO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA                = HOLDREGISTER_DEVICEPARAM_ALARM_LOW_AO + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA                = HOLDREGISTER_DEVICEPARAM_INITIAL_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA                 = HOLDREGISTER_DEVICEPARAM_AO_HIGH_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA                  = HOLDREGISTER_DEVICEPARAM_AO_LOW_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA                  = HOLDREGISTER_DEVICEPARAM_FAULT_CURRENT_mA + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED26                        = HOLDREGISTER_DEVICEPARAM_DEBUG_CURRENT_mA + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED27                        = HOLDREGISTER_DEVICEPARAM_RESERVED26 + REG_STRIDE,

    /* -------- 指令参数 -------- */
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL               = HOLDREGISTER_DEVICEPARAM_RESERVED27 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL             = HOLDREGISTER_DEVICEPARAM_CALIBRATE_OIL_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION                  = HOLDREGISTER_DEVICEPARAM_CALIBRATE_WATER_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION               = HOLDREGISTER_DEVICEPARAM_SP_MEAS_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL    = HOLDREGISTER_DEVICEPARAM_SP_MONITOR_POSITION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE            = HOLDREGISTER_DEVICEPARAM_DENSITY_DISTRIBUTION_OIL_LEVEL + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED28                        = HOLDREGISTER_DEVICEPARAM_MOTOR_COMMAND_DISTANCE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED29                        = HOLDREGISTER_DEVICEPARAM_RESERVED28 + REG_STRIDE,

    /* -------- 液位/水位与尺带温度补偿参数 -------- */
    HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL         = HOLDREGISTER_DEVICEPARAM_RESERVED29 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE        = HOLDREGISTER_DEVICEPARAM_LAST_OIL_CORRECTION_LEVEL + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT        = HOLDREGISTER_DEVICEPARAM_TANK_GAS_PHASE_TEMPERATURE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE      = HOLDREGISTER_DEVICEPARAM_TAPE_EXPANSION_COEFFICIENT + REG_STRIDE,

    HOLDREGISTER_DEVICEPARAM_RESERVED30                        = HOLDREGISTER_DEVICEPARAM_TAPE_CALIBRATION_TEMPERATURE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED31                        = HOLDREGISTER_DEVICEPARAM_RESERVED30 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED32                        = HOLDREGISTER_DEVICEPARAM_RESERVED31 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_RESERVED33                        = HOLDREGISTER_DEVICEPARAM_RESERVED32 + REG_STRIDE,

    /* -------- 元信息与 CRC -------- */
    HOLDREGISTER_DEVICEPARAM_PARAM_VERSION                     = HOLDREGISTER_DEVICEPARAM_RESERVED33 + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE                       = HOLDREGISTER_DEVICEPARAM_PARAM_VERSION + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_MAGIC                             = HOLDREGISTER_DEVICEPARAM_STRUCT_SIZE + REG_STRIDE,
    HOLDREGISTER_DEVICEPARAM_CRC                               = HOLDREGISTER_DEVICEPARAM_MAGIC + REG_STRIDE,

    /* 结束标志：下一个可用地址 */
    HOLEREGISTER_STOP                                          = HOLDREGISTER_DEVICEPARAM_CRC + REG_STRIDE
} HOLD;


/* ==================== CPU3 本机参数段（独立地址空间） ==================== */
#define HOLDREGISTER_CPU3_BASE	0x0200	/* 建议：CPU3 段起始地址，与 CPU2 段隔离 */

/* --- 屏幕 / 基本信息 --- */
#define HOLDREGISTER_CPU3_LED_VERSION	(HOLDREGISTER_CPU3_BASE + 0x00)	/* u16，仍按2寄存器占位 */
#define HOLDREGISTER_CPU3_LANGUAGE	(HOLDREGISTER_CPU3_BASE + 0x02)

/* --- 数据源选择 --- */
#define HOLDREGISTER_CPU3_SRC_OIL	(HOLDREGISTER_CPU3_BASE + 0x04)
#define HOLDREGISTER_CPU3_SRC_WATER	(HOLDREGISTER_CPU3_BASE + 0x06)
#define HOLDREGISTER_CPU3_SRC_D	(HOLDREGISTER_CPU3_BASE + 0x08)
#define HOLDREGISTER_CPU3_SRC_T	(HOLDREGISTER_CPU3_BASE + 0x0A)

/* --- 手工输入 --- */
#define HOLDREGISTER_CPU3_IN_OIL	(HOLDREGISTER_CPU3_BASE + 0x0C)
#define HOLDREGISTER_CPU3_IN_WATER	(HOLDREGISTER_CPU3_BASE + 0x0E)
#define HOLDREGISTER_CPU3_IN_D	(HOLDREGISTER_CPU3_BASE + 0x10)
#define HOLDREGISTER_CPU3_IN_D_SW	(HOLDREGISTER_CPU3_BASE + 0x12)
#define HOLDREGISTER_CPU3_IN_T	(HOLDREGISTER_CPU3_BASE + 0x14)

/* --- 显示类参数 --- */
#define HOLDREGISTER_CPU3_DECIMAL	(HOLDREGISTER_CPU3_BASE + 0x16)
#define HOLDREGISTER_CPU3_PASSWORD	(HOLDREGISTER_CPU3_BASE + 0x18)
#define HOLDREGISTER_CPU3_OFF_TIME	(HOLDREGISTER_CPU3_BASE + 0x1A)

/* --- COM1 --- */
#define HOLDREGISTER_CPU3_COM1_BAUD	(HOLDREGISTER_CPU3_BASE + 0x20)
#define HOLDREGISTER_CPU3_COM1_DATABITS	(HOLDREGISTER_CPU3_BASE + 0x22)
#define HOLDREGISTER_CPU3_COM1_PARITY	(HOLDREGISTER_CPU3_BASE + 0x24)
#define HOLDREGISTER_CPU3_COM1_STOPBITS	(HOLDREGISTER_CPU3_BASE + 0x26)
#define HOLDREGISTER_CPU3_COM1_PROTO	(HOLDREGISTER_CPU3_BASE + 0x28)

/* --- COM2 --- */
#define HOLDREGISTER_CPU3_COM2_BAUD	(HOLDREGISTER_CPU3_BASE + 0x30)
#define HOLDREGISTER_CPU3_COM2_DATABITS	(HOLDREGISTER_CPU3_BASE + 0x32)
#define HOLDREGISTER_CPU3_COM2_PARITY	(HOLDREGISTER_CPU3_BASE + 0x34)
#define HOLDREGISTER_CPU3_COM2_STOPBITS	(HOLDREGISTER_CPU3_BASE + 0x36)
#define HOLDREGISTER_CPU3_COM2_PROTO	(HOLDREGISTER_CPU3_BASE + 0x38)

/* --- COM3 --- */
#define HOLDREGISTER_CPU3_COM3_BAUD	(HOLDREGISTER_CPU3_BASE + 0x40)
#define HOLDREGISTER_CPU3_COM3_DATABITS	(HOLDREGISTER_CPU3_BASE + 0x42)
#define HOLDREGISTER_CPU3_COM3_PARITY	(HOLDREGISTER_CPU3_BASE + 0x44)
#define HOLDREGISTER_CPU3_COM3_STOPBITS	(HOLDREGISTER_CPU3_BASE + 0x46)
#define HOLDREGISTER_CPU3_COM3_PROTO	(HOLDREGISTER_CPU3_BASE + 0x48)


/*保持寄存器详细地址*/

/*输入寄存器详细地址*/

/* 输入寄存器详细地址 */

/* 每个字段占 2 个保持寄存器 */
#define REG_SIZE_U32    2
#define REG_SIZE_FLOAT  2
#define REG_SIZE_I32    2
#define REG_SIZE_U8     2   /* uint8 也占两个寄存器，保持对齐一致 */

/* ==== DeviceStatus ==== */
#define REG_DEVICE_STATUS_WORK_MODE             (0)
#define REG_DEVICE_STATUS_DEVICE_STATE          (REG_DEVICE_STATUS_WORK_MODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ERROR_CODE            (REG_DEVICE_STATUS_DEVICE_STATE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_CURRENT_COMMAND       (REG_DEVICE_STATUS_ERROR_CODE + REG_SIZE_U32)
#define REG_DEVICE_STATUS_ZERO_POINT_STATUS     (REG_DEVICE_STATUS_CURRENT_COMMAND + REG_SIZE_U32)

/* ==== DebugData ==== */
#define REG_DEBUG_BASE                          (REG_DEVICE_STATUS_ZERO_POINT_STATUS + REG_SIZE_U32)

#define REG_DEBUG_CURRENT_ENCODER               (REG_DEBUG_BASE + 0)
#define REG_DEBUG_SENSOR_POSITION               (REG_DEBUG_CURRENT_ENCODER + REG_SIZE_I32)
#define REG_DEBUG_CABLE_LENGTH                  (REG_DEBUG_SENSOR_POSITION + REG_SIZE_I32)

/* 新增：motor_step / motor_distance（与你当前 DebugData 结构一致） */
#define REG_DEBUG_MOTOR_STEP                    (REG_DEBUG_CABLE_LENGTH + REG_SIZE_I32)
#define REG_DEBUG_MOTOR_DISTANCE                (REG_DEBUG_MOTOR_STEP + REG_SIZE_I32)

#define REG_DEBUG_FREQUENCY                     (REG_DEBUG_MOTOR_DISTANCE + REG_SIZE_I32)
#define REG_DEBUG_TEMPERATURE                   (REG_DEBUG_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_AIR_FREQUENCY                 (REG_DEBUG_TEMPERATURE + REG_SIZE_U32)
#define REG_DEBUG_CURRENT_AMPLITUDE             (REG_DEBUG_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_DEBUG_WATER_LEVEL_VOLTAGE           (REG_DEBUG_CURRENT_AMPLITUDE + REG_SIZE_U32)

#define REG_DEBUG_CURRENT_WEIGHT                (REG_DEBUG_WATER_LEVEL_VOLTAGE + REG_SIZE_U32)
#define REG_DEBUG_WEIGHT_PARAM                  (REG_DEBUG_CURRENT_WEIGHT + REG_SIZE_U32)

#define REG_DEBUG_ANGLE_X                       (REG_DEBUG_WEIGHT_PARAM + REG_SIZE_U32)
#define REG_DEBUG_ANGLE_Y                       (REG_DEBUG_ANGLE_X + REG_SIZE_I32)

#define REG_DEBUG_MOTOR_SPEED                   (REG_DEBUG_ANGLE_Y + REG_SIZE_I32)
#define REG_DEBUG_MOTOR_STATE                   (REG_DEBUG_MOTOR_SPEED + REG_SIZE_U32)

/* ==== OilMeasurement ==== */
#define REG_OIL_MEASUREMENT_OIL_LEVEL           (REG_DEBUG_MOTOR_STATE + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_AIR_FREQUENCY       (REG_OIL_MEASUREMENT_OIL_LEVEL + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_OIL_FREQUENCY       (REG_OIL_MEASUREMENT_AIR_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY    (REG_OIL_MEASUREMENT_OIL_FREQUENCY + REG_SIZE_U32)
#define REG_OIL_MEASUREMENT_CURRENT_FREQUENCY   (REG_OIL_MEASUREMENT_FOLLOW_FREQUENCY + REG_SIZE_U32)

/* ==== WaterMeasurement ==== */
#define REG_WATER_MEASUREMENT_WATER_LEVEL       (REG_OIL_MEASUREMENT_CURRENT_FREQUENCY + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_ZERO_CAPACITANCE  (REG_WATER_MEASUREMENT_WATER_LEVEL + REG_SIZE_U32)
#define REG_WATER_MEASUREMENT_OIL_CAPACITANCE   (REG_WATER_MEASUREMENT_ZERO_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE (REG_WATER_MEASUREMENT_OIL_CAPACITANCE + REG_SIZE_FLOAT)

/* ==== ActualHeightMeasurement ==== */
#define REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL (REG_WATER_MEASUREMENT_CURRENT_CAPACITANCE + REG_SIZE_FLOAT)
#define REG_HEIGHT_MEASUREMENT_CURRENT_REAL     (REG_HEIGHT_MEASUREMENT_CAL_LIQUID_LEVEL + REG_SIZE_U32)

/* ==== Single Point Measurement ==== */
#define REG_SINGLE_POINT_MEAS_TEMP              (REG_HEIGHT_MEASUREMENT_CURRENT_REAL + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_DENSITY           (REG_SINGLE_POINT_MEAS_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_TEMP_POS          (REG_SINGLE_POINT_MEAS_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_STD_DENSITY       (REG_SINGLE_POINT_MEAS_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_VCF20             (REG_SINGLE_POINT_MEAS_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY    (REG_SINGLE_POINT_MEAS_VCF20 + REG_SIZE_U32)

/* ==== Single Point Monitoring ==== */
#define REG_SINGLE_POINT_MON_TEMP               (REG_SINGLE_POINT_MEAS_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_DENSITY            (REG_SINGLE_POINT_MON_TEMP + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_TEMP_POS           (REG_SINGLE_POINT_MON_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_STD_DENSITY        (REG_SINGLE_POINT_MON_TEMP_POS + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_VCF20              (REG_SINGLE_POINT_MON_STD_DENSITY + REG_SIZE_U32)
#define REG_SINGLE_POINT_MON_WEIGHT_DENSITY     (REG_SINGLE_POINT_MON_VCF20 + REG_SIZE_U32)

/* ==== Density Distribution Averages ==== */
#define REG_DENSITY_DIST_AVG_TEMP               (REG_SINGLE_POINT_MON_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_DENSITY            (REG_DENSITY_DIST_AVG_TEMP + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_STD_DENSITY        (REG_DENSITY_DIST_AVG_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_VCF20              (REG_DENSITY_DIST_AVG_STD_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_AVG_WEIGHT_DENSITY     (REG_DENSITY_DIST_AVG_VCF20 + REG_SIZE_U32)
#define REG_DENSITY_DIST_MEAS_POINTS            (REG_DENSITY_DIST_AVG_WEIGHT_DENSITY + REG_SIZE_U32)
#define REG_DENSITY_DIST_OIL_LEVEL              (REG_DENSITY_DIST_MEAS_POINTS + REG_SIZE_U32)

/* ==== Density Distribution Single Data ==== */
#define REG_DENSITY_DIST_POINT_BASE             (REG_DENSITY_DIST_OIL_LEVEL + REG_SIZE_U32)
#define REG_DENSITY_DIST_POINT_SIZE             (6 * REG_SIZE_U32) /* 每个测量点6个uint32 */

#define REG_DENSITY_POINT_TEMP(i)               (REG_DENSITY_DIST_POINT_BASE + (i) * REG_DENSITY_DIST_POINT_SIZE)
#define REG_DENSITY_POINT_DENSITY(i)            (REG_DENSITY_POINT_TEMP(i) + REG_SIZE_U32)
#define REG_DENSITY_POINT_TEMP_POS(i)           (REG_DENSITY_POINT_TEMP(i) + 2 * REG_SIZE_U32)
#define REG_DENSITY_POINT_STD_DENSITY(i)        (REG_DENSITY_POINT_TEMP(i) + 3 * REG_SIZE_U32)
#define REG_DENSITY_POINT_VCF20(i)              (REG_DENSITY_POINT_TEMP(i) + 4 * REG_SIZE_U32)
#define REG_DENSITY_POINT_WEIGHT_DENSITY(i)     (REG_DENSITY_POINT_TEMP(i) + 5 * REG_SIZE_U32)

/* ==== 最终寄存器数量 ==== */
#define REG_ENG (REG_DENSITY_DIST_POINT_BASE + MAX_MEASUREMENT_POINTS * REG_DENSITY_DIST_POINT_SIZE)

#define INPUTREGISTER_AMOUNT (REG_ENG)




/*报警状态*/
#define ALARMSTATE_NONE 0
#define ALARMSTATE_LOW 1
#define ALARMSTATE_HIGH 2

/*平均温度状态*/
#define AVETEMPERATURESTATE_UNVALID 0
#define AVETEMPERATURESTATE_VALID 1

/*平均密度状态*/
#define AVERAGEDENSITY_UNVALID 0
#define AVERAGEDENSITY_VALID 1

/*水位状态*/
#define WATER_UNVALID 0
#define WATER_VALID 1


#endif
