#ifndef _STATEFORMODBUS_H
#define _STATEFORMODBUS_H


/*功能码*/
#define FUNCTIONCODE_READ_HOLDREGISTER    0x03
#define FUNCTIONCODE_READ_INPUTREGISTER   0x04
#define FUNCTIONCODE_WRITE_COIL           0x05
#define FUNCTIONCODE_WRITE_MULREGISTER    0x10

/* 保持寄存器地址 */
#define HOLDREG_BASE_DEVICEPARAM 0x00

typedef enum {
    HOLDREGISTER_DEVICEPARAM_TANKHEIGHT = HOLDREG_BASE_DEVICEPARAM,
    HOLDREGISTER_DEVICEPARAM_BLINDZONE = HOLDREGISTER_DEVICEPARAM_TANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM = HOLDREGISTER_DEVICEPARAM_BLINDZONE + 2,
    HOLDREGISTER_DEVICEPARAM_SENSORTYPE = HOLDREGISTER_DEVICEPARAM_ENCODER_WHEEL_CIRCUMFERENCE_MM + 2,
    HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION = HOLDREGISTER_DEVICEPARAM_SENSORTYPE + 2,
    HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT = HOLDREGISTER_DEVICEPARAM_SOFTWAREVERSION + 2,
    HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION = HOLDREGISTER_DEVICEPARAM_EMPTY_WEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION = HOLDREGISTER_DEVICEPARAM_DENSITYCORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT = HOLDREGISTER_DEVICEPARAM_TEMPERATURECORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT = HOLDREGISTER_DEVICEPARAM_REQUIREBOTTOMMEASUREMENT + 2,
    HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY = HOLDREGISTER_DEVICEPARAM_REQUIREWATERMEASUREMENT + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER = HOLDREGISTER_DEVICEPARAM_REQUIRESINGLEPOINTDENSITY + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTORDER + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTMODE + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTCOUNT + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADMEASUREMENTDISTANCE + 2,
    HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT = HOLDREGISTER_DEVICEPARAM_SPREADTOPLIMIT + 2,
    HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION = HOLDREGISTER_DEVICEPARAM_SPREADBOTTOMLIMIT + 2,
    HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE = HOLDREGISTER_DEVICEPARAM_WATERLEVELCORRECTION + 2,
    HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG = HOLDREGISTER_DEVICEPARAM_MAXDOWNDISTANCE + 2,
    HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION = HOLDREGISTER_DEVICEPARAM_REFRESHTANKHEIGHTFLAG + 2,
    HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT = HOLDREGISTER_DEVICEPARAM_MAXTANKHEIGHTDEVIATION + 2,
    HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT = HOLDREGISTER_DEVICEPARAM_INITIALTANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD = HOLDREGISTER_DEVICEPARAM_CURRENTTANKHEIGHT + 2,
    HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD = HOLDREGISTER_DEVICEPARAM_OILLEVELTHRESHOLD + 2,
    HOLDREGISTER_DEVICEPARAM_CRC = HOLDREGISTER_DEVICEPARAM_LIQUIDLEVELMEASUREMENTMETHOD + 2,
	HOLEREGISTER_STOP = (HOLDREGISTER_DEVICEPARAM_CRC + 1) // 保持寄存器结束标志
} HOLD;

/*保持寄存器详细地址*/

/*输入寄存器详细地址*/
#define STARTADDRESS_INPUTREGISTER 0x00 /*输入寄存器的起始地址*/
#define INPUTREGISTER_VALUE_LEVEL  0x00 //液位
#define INPUTREGISTER_STATE_LEVEL  0x02 //液位计状态
#define INPUTREGISTER_ERRORCODE    0x03 //错误码
#define INPUTREGISTER_STATE_ALARM  0x04 //报警状态
#define INPUTREGISTER_TYPEOFTHERMOMETER 0x05 //温度计类型
#define INPUTREGISTER_VALUE_AVERAGETEMPERATURE  0x06 //平均温度
#define INPUTREGISTER_STATE_AVERAGETEMPERATURE  0x07 //平均温度值状态
#define INPUTREGISTER_VALUE_AVERAGEDENSITY  0x08 //平均密度
#define INPUTREGISTER_STATE_AVERAGEDENSITY 0x09 //平均密度值状态
#define INPUTREGISTER_VALUE_WATER 0x0A //水位值
#define INPUTREGISTER_STATE_WATER 0x0C //水位状态
#define INPUTREGISTER_VALUE_DENSITY1 0x0D //密度1
#define INPUTREGISTER_POSITION_DENSITY1 0x0E //密度1的位置
#define INPUTREGISTER_VALUE_DENSITY2 0x10 
#define INPUTREGISTER_POSITION_DENSITY2 0x11 
#define INPUTREGISTER_VALUE_DENSITY3 0x13 
#define INPUTREGISTER_POSITION_DENSITY3 0x14 
#define INPUTREGISTER_VALUE_DENSITY4 0x16 
#define INPUTREGISTER_POSITION_DENSITY4 0x17 
#define INPUTREGISTER_VALUE_DENSITY5 0x19 
#define INPUTREGISTER_POSITION_DENSITY5 0x1A 
#define INPUTREGISTER_VALUE_DENSITY6 0x1C 
#define INPUTREGISTER_POSITION_DENSITY6 0x1D 
#define INPUTREGISTER_VALUE_DENSITY7 0x1F 
#define INPUTREGISTER_POSITION_DENSITY7 0x20 
#define INPUTREGISTER_VALUE_DENSITY8 0x22 
#define INPUTREGISTER_POSITION_DENSITY8 0x23 
#define INPUTREGISTER_VALUE_DENSITY9 0x25 
#define INPUTREGISTER_POSITION_DENSITY9 0x26 
#define INPUTREGISTER_VALUE_DENSITY10 0x28 
#define INPUTREGISTER_POSITION_DENSITY10 0x29 
#define INPUTREGISTER_VALUE_DENSITY11 0x2B 
#define INPUTREGISTER_POSITION_DENSITY11 0x2C 
#define INPUTREGISTER_VALUE_DENSITY12 0x2E 
#define INPUTREGISTER_POSITION_DENSITY12 0x2F 
#define INPUTREGISTER_VALUE_DENSITY13 0x31 
#define INPUTREGISTER_POSITION_DENSITY13 0x32 
#define INPUTREGISTER_VALUE_DENSITY14 0x34 
#define INPUTREGISTER_POSITION_DENSITY14 0x35 
#define INPUTREGISTER_VALUE_DENSITY15 0x37 
#define INPUTREGISTER_POSITION_DENSITY15 0x38 
#define INPUTREGISTER_VALUE_DENSITY16 0x3A 
#define INPUTREGISTER_POSITION_DENSITY16 0x3B 
#define INPUTREGISTER_VALUE_TEMPERATURE1 0x3D //实时温度1
#define INPUTREGISTER_POSITION_TEMPERATURE1 0x3E //实时温度1的位置
#define INPUTREGISTER_VALUE_TEMPERATURE2 0x40 
#define INPUTREGISTER_POSITION_TEMPERATURE2 0x41 
#define INPUTREGISTER_VALUE_TEMPERATURE3 0x43 
#define INPUTREGISTER_POSITION_TEMPERATURE3 0x44 
#define INPUTREGISTER_VALUE_TEMPERATURE4 0x46 
#define INPUTREGISTER_POSITION_TEMPERATURE4 0x47 
#define INPUTREGISTER_VALUE_TEMPERATURE5 0x49 
#define INPUTREGISTER_POSITION_TEMPERATURE5 0x4A 
#define INPUTREGISTER_VALUE_TEMPERATURE6 0x4C 
#define INPUTREGISTER_POSITION_TEMPERATURE6 0x4D 
#define INPUTREGISTER_VALUE_TEMPERATURE7 0x4F 
#define INPUTREGISTER_POSITION_TEMPERATURE7 0x50 
#define INPUTREGISTER_VALUE_TEMPERATURE8 0x52 
#define INPUTREGISTER_POSITION_TEMPERATURE8 0x53 
#define INPUTREGISTER_VALUE_TEMPERATURE9 0x55 
#define INPUTREGISTER_POSITION_TEMPERATURE9 0x56 
#define INPUTREGISTER_VALUE_TEMPERATURE10 0x58 
#define INPUTREGISTER_POSITION_TEMPERATURE10 0x59
#define INPUTREGISTER_VALUE_TEMPERATURE11 0x5B 
#define INPUTREGISTER_POSITION_TEMPERATURE11 0x5C 
#define INPUTREGISTER_VALUE_TEMPERATURE12 0x5E   
#define INPUTREGISTER_POSITION_TEMPERATURE12 0x5F 
#define INPUTREGISTER_VALUE_TEMPERATURE13 0x61 
#define INPUTREGISTER_POSITION_TEMPERATURE13 0x62 
#define INPUTREGISTER_VALUE_TEMPERATURE14 0x64 
#define INPUTREGISTER_POSITION_TEMPERATURE14 0x65 
#define INPUTREGISTER_VALUE_TEMPERATURE15 0x67 
#define INPUTREGISTER_POSITION_TEMPERATURE15 0x68 
#define INPUTREGISTER_VALUE_TEMPERATURE16 0x6A 
#define INPUTREGISTER_POSITION_TEMPERATURE16 0x6B 
#define INPUTREGISTER_VALUE_GETWEIGHT 0x6D //称重值
#define INPUTREGISTER_VALUE_MOTORSTEPS 0x6E //电机步进数
#define INPUTREGISTER_VALUE_TEMPERATURE 0x70 //无线温度值
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE1 0x71//无线温度1
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE1 0x72//无线温度1位置
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE2 0x74
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE2 0x75
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE3 0x77
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE3 0x78
#define INPUTREGISTER_VALUE_TEMPERATUREASSIGNHEIGHT 0x7A//指定高度测量的温度值
#define INPUTREGISTER_POSITION_DENSITYASSIGNHEIGHT 0x7B//指定高度测量的位置
#define INPUTREGISTER_VALUE_DENSITYASSIGNHEIGHT 0x7D//指定高度测量的密度值
#define INPUTREGISTER_VALUE_SPOTSOFDENSITY 0x7E //测量密度的实际点数
#define INPUTREGISTER_VALUE_TANKHEIGHT 0x7F //罐高
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE4 0x81//无线温度4
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE4 0x82//无线温度4的位置
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE5 0x84
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE5 0x85
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE6 0x87
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE6 0x88
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE7 0x8A
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE7 0x8B
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE8 0x8D
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE8 0x8E
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE9 0x90
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE9 0x91
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE10 0x93
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE10 0x94
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE11 0x96
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE11 0x97
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE12 0x99
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE12 0x9A
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE13 0x9C
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE13 0x9D
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE14 0x9F
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE14 0xA0
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE15 0xA2
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE15 0xA3
#define INPUTREGISTER_VALUE_WIRELESSTEMPERATURE16 0xA5
#define INPUTREGISTER_POSITION_WIRELESSTEMPERATURE16 0xA6
#define INPUTREGISTER_PRESSUREP1 0XA8//压力传感器P1
#define INPUTREGISTER_PRESSUREP2 0XAA//压力传感器P2

//100个密度点
#define INPUTREGISTER_VALIDPOINTS 0XAC                                          //密度有效点数
#define INPUTREGISTER_DENSITYTYPE 0XAD                                          //密度模式
#define INPUTREGISTER_DENSITY_1 (0XAE)                                          //点1-密度
#define INPUTREGISTER_WIRELESSTEMP_1 (INPUTREGISTER_DENSITY_1 + 1)              //点1-温度
#define INPUTREGISTER_POSITION_1 (INPUTREGISTER_WIRELESSTEMP_1 + 1)             //点1-位置
#define INPUTREGISTER_DENSITY20_1 (INPUTREGISTER_POSITION_1 + 2)                //点1-标密
#define INPUTREGISTER_VCF_1 (INPUTREGISTER_DENSITY20_1 + 1)                     //点1-VCF
#define INPUTREGISTER_DENSITYGW_1 (INPUTREGISTER_VCF_1 + 2)                     //点1-计重密度
#define INPUTREGISTER_100END (INPUTREGISTER_DENSITYGW_1 + 8 * (100 - 1) + 1)    //100个密度点结束后,下一个寄存器地址

#define INPUTREGISTER_DENSITY_SINGLE (INPUTREGISTER_100END)                     //单点-密度
#define INPUTREGISTER_WIRELESSTEMP_SINGLE (INPUTREGISTER_DENSITY_SINGLE + 1)    //单点-温度
#define INPUTREGISTER_POSITION_SINGLE (INPUTREGISTER_WIRELESSTEMP_SINGLE + 1)   //单点-位置
#define INPUTREGISTER_DENSITY20_SINGLE (INPUTREGISTER_POSITION_SINGLE + 2)      //单点-标密
#define INPUTREGISTER_VCF_SINGLE (INPUTREGISTER_DENSITY20_SINGLE + 1)           //单点-VCF
#define INPUTREGISTER_DENSITYGW_SINGLE (INPUTREGISTER_VCF_SINGLE + 2)           //单点-计重密度
//新轮询协议段
enum{
    INPUTREGISTER_NEW_VALUE_LEVEL = (INPUTREGISTER_DENSITYGW_SINGLE + 1),       //液位
    INPUTREGISTER_NEW_STATE_LEVEL = (INPUTREGISTER_NEW_VALUE_LEVEL + 2),        //液位计状态
    INPUTREGISTER_NEW_ERRORCODE = (INPUTREGISTER_NEW_STATE_LEVEL + 1),          //故障代码
    INPUTREGISTER_NEW_STATE_ALARM = (INPUTREGISTER_NEW_ERRORCODE + 1),          //报警状态
    INPUTREGISTER_NEW_TYPEOFTHERMOMETER = (INPUTREGISTER_NEW_STATE_ALARM + 1),  //温度计类型
    INPUTREGISTER_NEW_VALUE_AVERAGETEMPERATURE = (INPUTREGISTER_NEW_TYPEOFTHERMOMETER + 1),         //平均温度
    INPUTREGISTER_NEW_STATE_AVERAGETEMPERATURE = (INPUTREGISTER_NEW_VALUE_AVERAGETEMPERATURE + 1),  //平均温度状态
    INPUTREGISTER_NEW_VALUE_AVERAGEDENSITY = (INPUTREGISTER_NEW_STATE_AVERAGETEMPERATURE + 1),      //平均密度
    INPUTREGISTER_NEW_STATE_AVERAGEDENSITY = (INPUTREGISTER_NEW_VALUE_AVERAGEDENSITY + 1),          //平均密度状态
    INPUTREGISTER_NEW_VALUE_WATER = (INPUTREGISTER_NEW_STATE_AVERAGEDENSITY + 1),                   //水位值
    INPUTREGISTER_NEW_STATE_WATER = (INPUTREGISTER_NEW_VALUE_WATER + 2),        //水位状态
    INPUTREGISTER_NEW_PRESSUREP1 = (INPUTREGISTER_NEW_STATE_WATER + 1),         //压力1
    INPUTREGISTER_NEW_PRESSUREP2 = (INPUTREGISTER_NEW_PRESSUREP1 + 2),          //压力2
    INPUTREGISTER_NEW_DISPLACERPOSI = (INPUTREGISTER_NEW_PRESSUREP2 + 2),       //浮子位置
    INPUTREGISTER_NEW_DENSITY20 = (INPUTREGISTER_NEW_DISPLACERPOSI + 2),        //平均标密
    INPUTREGISTER_NEW_VCF = (INPUTREGISTER_NEW_DENSITY20 + 1),                  //平均VCF
    INPUTREGISTER_NEW_DENSITYGW = (INPUTREGISTER_NEW_VCF + 2),                  //平均计重密度
    INPUTREGISTER_NEW_FOV = (INPUTREGISTER_NEW_DENSITYGW + 1),                  //水体积

    INPUTREGISTER_NEW_GOV = (INPUTREGISTER_NEW_FOV + 4),                        //净容积
    INPUTREGISTER_NEW_TOV = (INPUTREGISTER_NEW_GOV + 4),                        //油水总体积
    INPUTREGISTER_NEW_GSW = (INPUTREGISTER_NEW_TOV + 4),                        //质量
    INPUTREGISTER_NEW_CTSH = (INPUTREGISTER_NEW_GSW + 4),                       //罐壁修正系数
    INPUTREGISTER_NEW_GSV = (INPUTREGISTER_NEW_CTSH + 4),                       //毛标准体积
    INPUTREGISTER_NEW_WCF = (INPUTREGISTER_NEW_GSV + 4),                        //表观质量换算系数

    INPUTREGISTER_NEW_WEIGHT = (INPUTREGISTER_NEW_WCF + 4),                     //称重
    INPUTREGISTER_NEW_PIPEVELOCITY = (INPUTREGISTER_NEW_WEIGHT + 2),            //管道流速
    INPUTREGISTER_NEW_PIPEFLUX = (INPUTREGISTER_NEW_PIPEVELOCITY + 2),          //管道流量
    //正弦数组
    INPUTREGISTER_NEW_SINEPOINTS = (INPUTREGISTER_NEW_PIPEFLUX + 2),            //拟合总点数
    INPUTREGISTER_NEW_SINESTART = (INPUTREGISTER_NEW_SINEPOINTS + 1),           //拟合起始位置
    INPUTREGISTER_NEW_SINEEND = (INPUTREGISTER_NEW_SINESTART + 80 * 2),         //拟合结束位置

    
    
    NPUTREGISTER_NEW_END,//结束
};


#define INPUTREGISTER_AMOUNT (NPUTREGISTER_NEW_END)


/* 线圈指令地址 */
typedef enum{
     STARTADDRESS_COIL = 0x0A,                              //线圈起始地址
     COIL_FINDLEVEL = 0x0A,                                 //跟随液位
     COIL_MEASUREWATER = 0x0B,                              //测量水位
     COIL_MEASUREDENSITY = 0x0C,                            //密度测量
     COIL_CORRECTLEVEL = 0x0D,                              //修正液位
     COIL_MEASUREDENSITYANDTEMPERATURE = 0x0E,              //密度温度测量
     COIL_CALIBRATIONDENSITY = 0x0F,                        //密度校正
     COIL_CALIBRATIONORIGIN = 0x10,                         //标定零点
     COIL_CALIBRATIONLEVEL = 0x11,                          //标定液位
     COIL_BRINGUPDISPLACERTOORIGIN = 0x12,                  //提浮子至零点
     COIL_MEASUREDENSITY_ASSIGNHEIGHT = 0x13,               //指定高度密度测量
     COIL_MEASUREDENSITYANDTEMPERATURE_ASSIGNHEIGHT = 0x14, //指定高度密度温度测量
     COIL_MEASUREBOTTOM = 0x15,                             //罐底测量
     COIL_SYSTEMRESTART = 0x16,                             //系统重启
     COIL_RESERCOIL_INTEGRATEDVE6 = 0x17,                   //综合测量
     COIL_DENSITY_NATION = 0x18,                            //国标测量
     COIL_RESERVE7 = 0x19,
     COIL_RESTOREFACTORYSETTINGS = 0x1A,                    //恢复出厂设置
     COIL_BACKUPCONFIGURATIONFILE = 0x1B,
     COIL_RESTORECONFIGURATIONFILE = 0x1C,                  //恢复配置文件
     COIL_RESETSCOPEOFWEIGHT = 0x1D,                        //重置称重阈值
     COIL_GETVALUEOFWEIGHT = 0x1E,                          //读取称重值
     COIL_GETVALUEOFMOTORSTEPS = 0x1F,                      //读取步进数
     COIL_GETVALUEOFTEMPERATURE = 0x20,                     //读无线温度
     COIL_MOTORRUNUP = 0x21,                                //向上运行
     COIL_MOTORRUNDOWN = 0x22,                              //向下运行
     COIL_INTERVALMEASURE = 0x23,                           //区间测量
     COIL_PERMETERMEASURE = 0x24,                           //每米测量
     COIL_SELFINSPECTION = 0x25,                            //设备自检
     COIL_CONFIG = 0x26,                                    //进入仪表配置模式
     COIL_SETNOLOAD = 0x27,                                 //设置空载阈值
     COIL_SETFULLLOAD = 0x28,                               //设置满载阈值
     COIL_REDAREALTMP = 0x29,                               //读实时温度
     COIL_NOSINEFINDOIL= 0x2A,                              //无拟合找液位
     COIL_NOSINEZERO = 0x2B,                                //无拟合回零点
     COIL_VCHECK_STATIC,                                    //电压检测 - 静止
     COIL_VCHECK_RUN,                                       //电压检测 - 运动
     COIL_WATERFOLLOWING,                                   //水位跟随
     COIL_CORRECTWATERLEVEL,                                //修正水位
     COIL_EQUIPRUNNINGIN,                                   //设备磨合
     COIL_CHECKMODE,                                        //进入检修模式
     
     
     COIL_AMOUNT,//线圈总数
}COIL;


/*报警状态*/
#define ALARMSTATE_NONE 0
#define ALARMSTATE_LOW 1
#define ALARMSTATE_HIGH 2

/*平均温度状态*/
#define AVETEMPERATURESTATE_UNVALID 0
#define AVETEMPERATURESTATE_VALID 1

/*平均密度状态*/
#define AVERAGEDENSITY_UNVALID 0
#define AVERAGEDENSITY_VALID 1

/*水位状态*/
#define WATER_UNVALID 0
#define WATER_VALID 1


#endif
