name: Build LTD_MAIN_CPU2 (GCC+CMake+Ninja)

on:
  push:
    branches: ["MAIN", "main", "CMAKE", "MOTOR_TEXT"]
  pull_request:
    branches: ["MAIN", "main"]

jobs:
  build-cpu2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (CMake, Ninja, Arm GCC)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi

          cmake --version
          ninja --version
          arm-none-eabi-gcc --version

      - name: Configure
        run: |
          cmake -S LTD_MAIN_CPU2 -B build/LTD_MAIN_CPU2 -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-none-eabi.cmake \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build build/LTD_MAIN_CPU2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LTD_MAIN_CPU2-artifacts
          path: |
            build/LTD_MAIN_CPU2/*.elf
            build/LTD_MAIN_CPU2/*.hex
            build/LTD_MAIN_CPU2/*.bin
            build/LTD_MAIN_CPU2/*.map